### ISSUE TITLE
How to handle IncompleteRead errors while streaming

### ISSUE THREAD

**Issue by TayZ3r** [tweepy/tweepy#1557] opened 2021-03-29 12:58 UTC
Everytime I run my code for a long time, I get that type of error:

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/http/client.py", line 555, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/local/lib/python3.8/http/client.py", line 522, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/http/client.py", line 587, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/local/lib/python3.8/http/client.py", line 557, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 518, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.8/http/client.py", line 492, in readinto
    return self._readinto_chunked(b)
  File "/usr/local/lib/python3.8/http/client.py", line 603, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(2 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/tweepy/streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/tweepy/streaming.py", line 289, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python3.8/site-packages/tweepy/streaming.py", line 339, in _read_loop
    line = buf.read_line()
  File "/usr/local/lib/python3.8/site-packages/tweepy/streaming.py", line 200, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 540, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(2 bytes read)', IncompleteRead(2 bytes read))
```

I already try to edit streaming.py like [here](https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f)

I have no idea how to fix it, any help is welcomed

**Comment by ethankershner** [comment] 2021-03-29 16:11
I have been having this same issue, it will be solved in the next release I believe. I think the fix has been pushed to the main branch already but I was having issues installing from the main branch, but I believe that's one option to fix this before the release of 4.0.

**Comment by jamsspinle** [comment] 2021-03-30 22:34
I've encountered this problem quite a few times and came up with a work around. I created an asynchronous function that runs in the background and checks every so often if the stream is still running. If it's not, it will create another. It looks something like this:

```
async def listen():
  stream = #createStream
  
  while(True):
    if not stream.running:
      await asyncio.sleep(5)
      stream = #createStreamAgain

    else:
      await asyncio.sleep(5) 
```

The sleep statement immediately after the if statement may not be needed, but I added it incase the API got mad that another stream was created so quick. Hopefully this helps you.

**Comment by ethankershner** [comment] 2021-03-30 22:36
> I've encountered this problem quite a few times and came up with a work around. I created an asynchronous function that runs in the background and checks every so often if the stream is still running. If it's not, it will create another. It looks something like this:
> 
> ```
> async def listen():
>   stream = #createStream
>   
>   while(True):
>     if not stream.running:
>       await asyncio.sleep(5)
>       stream = #createStreamAgain
> 
>     else:
>       await asyncio.sleep(5) 
> ```
> 
> The sleep statement immediately after the if statement may not be needed, but I added it incase the API got mad that another stream was created so quick. Hopefully this helps you.

Thanks so much for this, I will try it out shortly.

**Comment by Harmon758** [comment] 2021-04-04 14:41
This should already be fixed in the master branch with the mentioned commit, https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f.
See also the relevant issues closed with that commit: #237, #448.

**Closed by Harmon758** 2021-04-04 14:41 UTC

**Comment by TayZ3r** [comment] 2021-04-04 15:05
I already apply e6819cc changes on my streaming.py file, I stil get the error as I mentioned

**Comment by ethankershner** [comment] 2021-04-04 15:09
> I already applied [68e19cc](https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f) changes on my streaming.py file, I stil get the error as I mentioned

You should install from the main branch instead of applying the changes on your own, see the readme.md for instructions on how to do that. You'll also want to subclass Streaming instead of StreamListener because those classes have been merged in the master branch version of Tweepy.

**Comment by Harmon758** [comment] 2021-04-04 15:29
Applying individual commits from the master branch to an older version is ill-advised, as there can likely be context missing from additional prior or subsequent commits on the master branch. Regardless, even if https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f was applied to v3.10 in the relevant parts of the code, that traceback would not be possible, since the error being raised is handled with that commit.

Manually modifying Tweepy itself is not reproducible and will not be supported. Instead, as noted, if you really need a change that hasn't been released yet, you should install the development version on the master branch, but there are other breaking changes currently on the master branch that you'll need to take into consideration. Otherwise, you should see the referenced issues for the likely cause of this issue.

Feel free to create a new issue if you're still able to reproduce this using the master branch.

**Comment by Technerder** [comment] 2021-06-04 05:22
Experiencing the same error on my installation (Tweepy 3.10.0 installed using pip)
```error
Traceback (most recent call last):
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 518, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 583, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 553, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 436, in _error_catcher
    yield
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 518, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 488, in readinto
    return self._readinto_chunked(b)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 599, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Technerder/Dev/Playground/twitter_streamer.py", line 14, in <module>
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 474, in filter
    self._start(is_async)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 389, in _start
    self._run()
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 289, in _run
    self._read_loop(resp)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 339, in _read_loop
    line = buf.read_line()
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\streaming.py", line 200, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 540, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Technerder\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by Harmon758** [comment] 2021-06-04 05:36
Again, this should already be fixed in the development version on the master branch.
