### ISSUE TITLE
Connection broken: IncompleteRead

### ISSUE THREAD

**Issue by truekonrads** [tweepy/tweepy#650] opened 2015-09-09 06:33 UTC
This happened and wasn't handled properly. Expected behaviour - reconnection

```
Traceback (most recent call last):¡ãç°¡å
  File "./feeder.py", line 78, in <module>
    stream.filter(**filterargs)
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 430, in filter
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 346, in _start
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 286, in _run
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 512 more expected)', IncompleteRead(0 bytes read, 512 more expected))
```

**Comment by pcarpio** [comment] 2015-11-24 18:47
This is happening to me as well, I updated to the last version which is 3.5.0... i think I'm getting this error everytime I lost connection with the server... I'm not 100% sure any help?

**Comment by gambolputty** [comment] 2015-12-25 03:58
Same with me:

`ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 3346 more expected)', IncompleteRead(0 bytes read, 3346 more expected))`

See #448 and #498.

Why am I still getting this error?

**Comment by Andergraw** [comment] 2016-02-20 20:12
Same here, even with Tweepy 3.5.0

**Comment by suryasekharmondal** [comment] 2016-06-16 14:59
Same problem here

**Comment by Melvinroy** [comment] 2016-08-03 18:26
Same issue .Could someone help me solve it?

**Comment by yummuy** [comment] 2017-04-19 12:10
Same problem for me too. Using python3.4 with tweepy 3.5.0 .

I tried to capture exception using:

```
except IncompleteRead:
:
:
except ProtocolError as pe:
:
except Exception as ex:
:
```

Exception details:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
    yield
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 529, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 558, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.4/http/client.py", line 650, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/usr/lib/python3.4/http/client.py", line 709, in _safe_readinto
    raise IncompleteRead(bytes(mvb[0:total_bytes]), len(b))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 512 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 179, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 512 more expected)', IncompleteRead(0 bytes read, 512 more expected))

```

**Comment by israa-ia1205702** [comment] 2017-05-03 16:43
I like this solution I will try it here is the link


http://stackoverflow.com/questions/26638329/incompleteread-error-when-retrieving-twitter-data-using-python

**Comment by aaronts9** [comment] 2017-05-04 06:11
how did this work out for you? Looking but can't seem to get it to work myself

**Comment by israa-ia1205702** [comment] 2017-05-04 07:04
Sorry for the false hope I said I will try it, not I did and it work. I am still working on it. If I have any updates I will tell you

kind Regards

**Comment by Sherm4nLC** [comment] 2017-08-06 21:45
Is there any error handling solution for this?

**Comment by raulmpimentel** [comment] 2018-02-28 12:50
I have the same problem. Has anyone had any progress?

**Comment by diegoje** [comment] 2018-03-15 14:25
Same problem here - anybody solved it?

**Comment by Vinodhkumar-MT16062** [comment] 2018-03-23 13:34
Is there any way to solve this problem?

**Comment by Vinodhkumar-MT16062** [comment] 2018-03-23 14:19
On simple method to handle/suppress the exception is to override the on_exception() function in tweepy streaming class.

**Comment by diegoje** [comment] 2018-03-23 14:57
would adding the above under on_data solve it?

**Comment by Vinodhkumar-MT16062** [comment] 2018-03-23 15:56
i don't think adding in on_data works.. just overriding on_exception() as i have done for example is simple and works perfectly.

**Comment by bbbbbw** [comment] 2018-04-11 06:51
Overriding on_exception() works but for me it seems that this exception is raised every 10 minutes, which is really annoying. Is it possible to solve it thoroughly?

**Comment by fedecaccia** [comment] 2018-04-29 18:40
It seems like you are trying to process to much each tweet, and this takes to much time, so twitter disconnects you. Just leave the process of the data to another thread.

**Comment by genesiscrew** [comment] 2018-06-11 22:34
for  tweepy v 3.5, the quick and dirty fix is to go to this function in your stream.py:  file def _run(self):
in the list of exceptions, just add ProtocolError.  you will need to import this by adding this your code: from urllib3.exceptions import ProtocolError

you might also want to comment out the snooze function inside the exception, if you dont want any delay in your real time capturing.

**Comment by adamfarnsworth** [comment] 2018-07-10 20:09
https://developer.twitter.com/en/docs/basics/rate-limiting.html

There is a limit at 15 minutes, so you just have to reconnect after it times out.

**Comment by Mitesh-C** [comment] 2019-03-03 16:44
> i don't think adding in on_data works.. just overriding on_exception() as i have done for example is simple and works perfectly.

i tried with your solution but it keeps coming same error again and again.
Is there any other method to solve it. 
Any help is appreciated

**Comment by Harmon758** [comment] 2019-04-26 22:25
Duplicate of #237

**Closed by Harmon758** 2019-04-26 22:25 UTC

**Comment by deadvin** [comment] 2021-08-09 11:27
One way to go around is to restart the stream in   def on_exception(self, exception): .
If you want to solve the problem you need to make your computations in def on_status(self, status): lighter or to move them out of the stream.
