### ISSUE TITLE
How to solve Tweepy stream on_status function not executing?

### ISSUE THREAD

**Issue by ScarletMcLearn** [tweepy/tweepy#1735] opened 2021-12-19 20:12 UTC
### Discussed in https://github.com/tweepy/tweepy/discussions/1734

<div type='discussions-op-text'>

<sup>Originally posted by **ScarletMcLearn** December 20, 2021</sup>
I have been using this script to Stream Tweets from Twitter.

I am trying to filter Tweets using Twitter Streaming API and perform operations on the Tweets as they come, and make Tweets or follow author if certain conditions are met.

It was working fine, but now it is not executing anything.

Can you please suggest how I can solve this?

Thank you!

Code -
```

class Few_Tweet_Printer(tweepy.Stream):
    counter = 0
    def on_status(self, status):
#         all_data = json.loads(status)
#         print(all_data)
        # Tweet Attributes
        tweet_id = status.id 
        screen_name = status.user.screen_name
        original_tweeter = ''
        created_on = status.created_at
        user_created_on = status.user.created_at
        user_location = status.user.location
        user_id = status.user.id_str
        location = status.geo
        is_truncated = status.truncated
        tweet_contributors = status.contributors
        place = status.place 
        geo = status.geo 
        coordinates = status.coordinates
        text = ''
        user_list = []   
        
#         print(tweet_id)
        self.counter = self.counter + 1
    
#         Print tweet info for testing - Can comment out on live
        print('Tweet number: ', self.counter)
        print('Tweet ID: ', tweet_id)
        print('Posted on: ', created_on)
        print('User ID: ', user_id)
        print('Username: ', screen_name)
        print('Place Posted In: ', place)
        print('Coordinates: ', coordinates)
        print('Geo: ', geo)
        
        
        
#         Print tweet info for testing - Can comment out on live        
        # Tweet Text ########################
        
        print('\n-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!')
        
        if not status.truncated:
            text = status.text
        else:
            text = status.extended_tweet['full_text']  
        print('Text: ', text)
        
        
        # Sentiment ##########################  Commenting for new model
            
#         sentence = Sentence(text)
#         classifier.predict(sentence)

#         # print sentence with predicted labels
#         print('Sentiment: ', sentence.labels)

            
        #####################################
        
        
        
        # Sentiment Ensemble Model ################
        
#         Print Ensamble Model results for testing - Can comment out on live
        
        print('\n-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!')
        
        if multi_senti(text)['Mean Score']  <= -0.3:
            print('Found match!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
        else:
            print('Not match!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
        
        print('\n-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!')
        
        ###########################################
        
        
        # User Details ######################
        
        print('Account Created on: ', user_created_on)
        print('Location: ', user_location)
        
        print('Geo: ', location)
#         print('User Attributes', dir(status.user))

#         screen_name = 'DasAshokDas1'


        # Adding Friend ############# Commenting out for testing

#         print('Before adding friend.')
#         try:
#             api.create_friendship(screen_name=screen_name)
#             if original_tweeter:
#                 api.create_friendship(screen_name=original_tweeter)
#             print('Friend added.')
#         except AttributeError as e:
#             print(e)
        
        #####################################################
        
        print('\n-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!')
        
        # Original User ####################
#         print(text[:2])

        if text[:2] == 'RT':
            start = text.find('@') + 1
#             print(start)
            end = text.find(':')
            original_tweeter = text[start:end]
            print('Original Tweeter: ', original_tweeter)
            user_list.append(original_tweeter)
        
# #         print('Source: ', status.source)
#         print('Is Retweet: ', tweet_contributors)
#         if status.retweeted:
#             print('Main author: '
#                   #, status.retweeted_status.author
#                  )
            
        ###################################
        
        user_list.append(screen_name)
        
        print('User list: ', user_list)
        
        for i in user_list:
            message_txt = 'enter text here'
            tweet_txt = '@' + i + ' hello there!'   # Tweet on profile   # Tweet text
#             if multi_senti(text)['Mean Score']  <= -0.3:
#                 create_tweet(api, tweet_txt)   # commenting these for test
#                 send_direct_message(get_twitter_id(i), message_txt)
        
        print('\n-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!')
          
        try:
            print('Is Truncated: ', is_truncated)
            
        
            print('\n###############################################################################################################################################################################')    

        except AttributeError as e:
            print(e)
        print('\n###############################################################################################################################################################################')    
        print()
        if self.counter == 5:
            tweepy.Stream.disconnect()


printer = Few_Tweet_Printer(
  CONSUMER_KEY, CONSUMER_SECRET,
  ACCESS_TOKEN, ACCESS_TOKEN_SECRET
)
# printer.sample()



printer.filter(
    track=['sad,depressed,hurt,kill myself,die,suicide,give up,hopeless,helpless,tired,alone,burden,pain,guilt,shame,alone,trapped,unbearable,anxious,agitated,crushed,',]   # For OR Logic - Need to pass as CSV - For AND Logic - Need to pass as SpaceSV 
    
#     locations=[c.bbox for c in country_subunits_by_iso_code(pycountry.countries.search_fuzzy('India')[0].alpha_2)]
              )
```</div>

**Comment by Harmon758** [comment] 2021-12-22 20:32
Duplicate of #1734

**Closed by Harmon758** 2021-12-22 20:32 UTC
