### ISSUE TITLE
Pagination with return_type=dict is not returning the "includes" section of a tweet.

### ISSUE THREAD

**Issue by wolfassi123** [tweepy/tweepy#1933] opened 2022-08-03 11:43 UTC
I just realized that there has been a lot of issues with the return_type = dict. First of all, pagination does not work, you need to change a few things in the .py file (you can check this repo "https://github.com/lqhuang/tweepy/tree/fix-meta-attr-for-paginator", in case there was still some more issues, just replace all the ".data" or ".meta" with "["data"]" or "["meta"]".

But now I realized that there is an issue with tweepy, where when using the pagination requests, the tweets that are being returned have a different format. The includes field is excluded. The issue is from tweepy's end. Has anyone implemented any fix to this?

**Comment by lqhuang** [comment] 2022-09-16 04:13
Are there some examples to show how and what content the `include` field is excluded? It would be helpful.

**Comment by lqhuang** [comment] 2022-09-16 04:20
I see, I have some same issues before, but I do not use `include` field in my case. I think it probably requires redesigning the `Pagination` model to resolve this.

**Comment by Harmon758** [comment] 2022-10-26 20:59
I'm unable to reproduce this:
```pycon
>>> for response in tweepy.Paginator(client.search_recent_tweets, "Twitter", expansions="author_id", limit=2):
...     print(response["includes"])
...
{'users': [{'id': '1318324869210296323', 'name': 'ReisyRedPanda', 'username': 'RedReisy'}, {'id': '1030560395440922625', 'name': 'Mohamed Mandour', 'username': 'momandour1975'}, {'id': '1071211799238692864', 'name': 'may⁷ 👩🏽\u200d🚀🌙', 'username': 'Jooniebrtz'}, {'id': '1584587498390540294', 'name': 'Megan Diaz', 'username': 'suzuragu1989'}, {'id': '1583752927348494337', 'name': 'Mehtap Özcan', 'username': 'Mehtapz58916980'}, {'id': '1024512511465455616', 'name': '$10 dm fee', 'username': 's8tanbaby'}, {'id': '1527517693', 'name': 'دجال و مورتى', 'username': 'dajal_morty'}, {'id': '1583336084825587714', 'name': 'Aykan Gül Özmen', 'username': 'ozmen_aykan'}, {'id': '917590358904553472', 'name': 'さーちゃん*°固ﾂｲ2🎁🥚🐔', 'username': 'sa33skr'}, {'id': '1078739004722421761', 'name': '🌙♡🇦🇷', 'username': '_ltzyeji'}]}
{'users': [{'id': '871796123836571650', 'name': 'Pınar Yüzbaşıoğlu', 'username': 'PinarYuzbasiog1'}, {'id': '884243660', 'name': 'Nicolaj Larsen', 'username': 'NicolajLarsen1'}, {'id': '1580231779633569794', 'name': 'FULLCLIP™', 'username': 'fullclipmaga'}, {'id': '326188316', 'name': 'Josh Kail', 'username': 'THATJoshKail'}, {'id': '1494776571994906626', 'name': 'COCO 💛MOMOTAサブ❣️ラブ❓💗ダイエッター楽しくハッピー❤️💛🐷入門します❓🌈', 'username': 'momota5555'}, {'id': '1402253153031032839', 'name': 'مصطفى حطبه', 'username': 'Moustaf74162085'}, {'id': '24001226', 'name': 'omar ali', 'username': 'omarali50'}, {'id': '1569980638853492739', 'name': 'ได้หมด', 'username': 'awiruth8888'}, {'id': '1582708385903960064', 'name': 'Flags1996_05 🇪🇪🇧🇷🇪🇪🇧🇷🇪🇪🇧🇷🇪🇪🇧🇷', 'username': 'Flags1996_05'}, {'id': '1495487878289260546', 'name': 'Eduardo', 'username': 'scatprime'}]}
```

Can you provide a reproducible example (MCVE/SSCCE) of what you're encountering?

The issues with pagination should be resolved with #1861.

**Comment by lqhuang** [comment] 2022-10-27 03:19
I didn't understand what he wants to say either, and I also forgot my special case I found in the past 😢

But after recheck Paginator, there is a problem that invoke [flatten](https://github.com/tweepy/tweepy/blob/2b1e159f4525df74e7cf9f2c531392966f306a82/tweepy/pagination.py#L61) method may raise `AttributeError`:

```
if response.data is not None:
```

`response` may do not have `.data` attribute when `response` isn't the default return type.

**Comment by Harmon758** [comment] 2022-10-27 18:02
That's not relevant to this issue, but I've fixed it now with https://github.com/tweepy/tweepy/commit/381bf9182700fa0c51df00b5b0f3e19c3d04dac0.

**Closed** 2022-11-11 19:37 UTC
Labels: Need Follow-Up, Question, No Reproduction
