### ISSUE TITLE
fail at import 

### ISSUE THREAD

**Issue by Chewbee** [tweepy/tweepy#1289] opened 2019-11-03 19:02 UTC
Sorry for this,  but I have a failure at import 

```
Traceback (most recent call last):
  File "twitterStream.py", line 7, in <module>
    import tweepy
  File "/usr/local/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/usr/local/lib/python3.7/site-packages/tweepy/streaming.py", line 355
    def _start(self, async):
                         ^
SyntaxError: invalid syntax
```
$ python3 --version
Python 3.7.4

**Comment by Harmon758** [comment] 2019-11-03 19:40
This is a duplicate of #1017 and was already fixed with #1042.
You're using an older version of Tweepy (<3.7.0) that doesn't support Python 3.7.
In the future, please make sure you're using the latest development version when reporting issues.

**Closed by Harmon758** 2019-11-03 19:40 UTC
