### ISSUE TITLE
Cleanup of issues

### ISSUE THREAD

**Issue by wodim** [tweepy/tweepy#834] opened 2017-01-09 15:03 UTC
No offence, but if the current maintainers don't have time to clean up all the issues, other users should be appointed to do so. More of half the recent issues are user errors that should not be marked as "open issues in tweepy". I volunteer to clean up and help if necessary.

**Comment by fitnr** [comment] 2017-01-10 03:30
I would mark this as a duplicate of #792 and close, but...

**Comment by dmwyatt** [comment] 2017-03-06 15:43
@Aaron1011 did you give up on this project?

**Comment by Harmon758** [comment] 2019-04-24 21:27
I've closed and labeled a significant number of issues today and will continue to do so.

**Closed by Harmon758** 2019-04-24 21:27 UTC
