### ISSUE TITLE
Muting user

### ISSUE THREAD

**Issue by alceal** [tweepy/tweepy#919] opened 2017-08-15 11:04 UTC
When can we expect muting to be integrated into the API wrapper?

**Comment by argysamo** [comment] 2017-11-06 14:51
Duplicate of #528 
Is anyone working on this one? 
Shall I try implement it and create a PR?

**Comment by antoinemcgrath** [comment] 2018-06-06 22:18
Ability to mute has been added https://github.com/tweepy/tweepy/pull/1055
I hope my addition will be approved by admin with write access.__

**Comment by Harmon758** [comment] 2019-04-25 04:29
Duplicate of #528

**Closed by Harmon758** 2019-04-25 04:29 UTC
