### ISSUE TITLE
api.update_status call in documentation

### ISSUE THREAD

**Issue by Anna-Livia** [tweepy/tweepy#644] opened 2015-08-29 11:18 UTC
In docs/auth_tutorial.rst, there is an example : "api.update_status('tweepy + oauth!')"
However, using api.update_status('tweepy + oauth!') creates an Twitter error 400.
To fix it, you have to write status =‘tweepy + oauth!’  in the
parameters —> api.update_status(status = ’tweepy + oauth!')
(fix found here http://stackoverflow.com/questions/19337672/post-tweet-with-tweepy )

Could you please change the documentation to reflect this and help beginners like me ?

Thank you for all your work !

**Comment by phylaxis** [comment] 2015-08-29 17:14
Anna, I too struggled with figuring this out, but it looks like there was something addressed in #578, but I really couldn't follow the thread and for me even running Tweepy 3.4.0 I still had to use the `status =` syntax.

**Comment by wjt** [comment] 2015-10-09 06:21
@phylaxis #578 was merged after the 3.4.0 release, and there's not been a release since, which is why you still need to use a named argument in the latest release.

**Comment by phylaxis** [comment] 2015-10-09 13:43
Ah, thanks. It wasn't clear to me.

**Comment by Anna-Livia** [comment] 2015-10-12 05:07
So, shouldn't the documentation be changed until the next release ? Or at least, explain the issue ?
What do you think ?

**Comment by wjt** [comment] 2015-10-12 07:59
@Anna-Livia I think a new release would be great (this fix is the only change merged since 3.4.0), but that's up to the maintainers.

**Comment by Harmon758** [comment] 2019-04-26 05:07
Duplicate of #554 
As mentioned, this is now fixed with https://github.com/tweepy/tweepy/commit/954b2f4868975b828e9af916c574716e089fdfd8 (#578), which has been released as part of Tweepy v3.5.0.

**Closed by Harmon758** 2019-04-26 05:07 UTC
