### ISSUE TITLE
send_direct_message api does not support sending options.

### ISSUE THREAD

**Issue by MohitKumar1991** [tweepy/tweepy#1394] opened 2020-06-19 07:57 UTC
The following API http://docs.tweepy.org/en/latest/api.html#API.send_direct_message does not support sending the options in case the `quick_reply_type` is options. I checked the source code and unfortunately it is being added like this. So only type is added and the options are not added.
<img width="481" alt="Screenshot 2020-06-19 at 1 25 44 PM" src="https://user-images.githubusercontent.com/1735701/85110361-6cb1fe00-b230-11ea-802d-30186b9b6dc6.png">

This is the twitter API reference - https://developer.twitter.com/en/docs/direct-messages/quick-replies/api-reference/options

Doesn't look there is a workaround for now. Please suggest any workaround you can think of.

**Comment by Harmon758** [comment] 2020-07-01 17:59
Duplicate of #1280

**Closed by Harmon758** 2020-07-01 17:59 UTC
