### ISSUE TITLE
Problem with client using streamer

### ISSUE THREAD

**Issue by Luiscri** [tweepy/tweepy#1265] opened 2019-09-05 11:39 UTC
I'm having a problem with a client failing on reading certain bytes. I don't know much about the problem, but it happens with a python script which worked perfectly before.

I'm trying it on WSL and the streamer starts and generates the files containing the tweets propertly for a while, but after a couple of hours working it stops and displays the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/http/client.py", line 546, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.6/http/client.py", line 513, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/http/client.py", line 578, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.6/http/client.py", line 548, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luisc/.local/lib/python3.6/site-packages/urllib3/response.py", line 397, in _error_catcher
    yield
  File "/home/luisc/.local/lib/python3.6/site-packages/urllib3/response.py", line 479, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 483, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.6/http/client.py", line 594, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "startStreaming.py", line 109, in <module>
    stream.filter(locations=locations, languages=languages)
  File "/home/luisc/.local/lib/python3.6/site-packages/tweepy/streaming.py", line 474, in filter
    self._start(is_async)
  File "/home/luisc/.local/lib/python3.6/site-packages/tweepy/streaming.py", line 389, in _start
    self._run()
  File "/home/luisc/.local/lib/python3.6/site-packages/tweepy/streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "/home/luisc/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/luisc/.local/lib/python3.6/site-packages/tweepy/streaming.py", line 289, in _run
    self._read_loop(resp)
  File "/home/luisc/.local/lib/python3.6/site-packages/tweepy/streaming.py", line 339, in _read_loop
    line = buf.read_line()
  File "/home/luisc/.local/lib/python3.6/site-packages/tweepy/streaming.py", line 200, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "/home/luisc/.local/lib/python3.6/site-packages/urllib3/response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/luisc/.local/lib/python3.6/site-packages/urllib3/response.py", line 415, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

Any idea what is happening? As I say the same script worked perfectly before and no changes has been made to it, but if it was necessary I can upload the script I'm using.

**Comment by AhsanSheraz** [comment] 2019-09-28 14:28
Same Error I face and the problem was I process thousand of tweets in a data structure which took a lot of memory. Due to this tweepy disconnect connection from Twitter, I just resolve it by just process tweets chunk by chunk, not whole tweets. Actually, it's a dynamic approach to solve algorithmic problems. Hope this will work for you.

**Comment by Luiscri** [comment] 2019-10-02 10:46
Do you mean by retrieving thousand of tweets or by saving them? I ask tweepy for the full metadata although I only save some of the fields, is there a way to ask only for those specific fields in order to avoid that error?

**Comment by Harmon758** [comment] 2019-10-13 01:57
> is there a way to ask only for those specific fields in order to avoid that error?

No, but that isn't the direct cause of the issue, which is a duplicate of #237 (and #448).

**Closed by Harmon758** 2019-10-13 01:57 UTC
