### ISSUE TITLE
StreamListener userstream 410 error (resource not found)

### ISSUE THREAD

**Issue by jaguarpaw249** [tweepy/tweepy#1092] opened 2018-08-22 03:56 UTC
I think the user stream API is deprecated.

This is due to be completely removed on August 23rd, but ahead of that date, the endpoints are being periodically switched off to remind developers that they need to migrate to an alternative method such as the Account Activity API.

**Comment by Harmon758** [comment] 2018-08-22 11:40
Duplicate of #1046, #1075, and #1081

**Comment by Michael-M-Judd** [comment] 2018-08-24 20:09
Sadly UserStream is no longer available. I wish that Twitter made this known a bit better! If you're like me and was using UserStream to get your own accounts home timeline, I think we now have to pay for the service 😢

**Comment by jaguarpaw249** [comment] 2018-08-27 02:28
We can use the following two APIs which will work in conjunction with each other:
1) home_timeline: 15 requests per 15 min window (1 request / min)
2) user_timeline: 900 requests per 15 min window (60 request / min)

As we'll hit the home_timeline API after every 1 minute, the maximum time delay for any tweet will be 1 minute.
**Average time delay** - 0 - 60 seconds (edited)

It is possible that the rate time limit for home_timeline API may exceed. (Based on the traffic from our server). In such a case the user_timeline API will iterate over all the followed users to scrape the recent tweets.
**Worst case delay** - up to 4 minutes

**Comment by Harmon758** [comment] 2019-04-28 03:33
User and Site streams have been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734

**Closed by Harmon758** 2019-04-28 03:33 UTC
