### ISSUE TITLE
Streaming.py Crash on Incomplete Read Error when tweets are very high...

### ISSUE THREAD

**Issue by jamesfebin** [tweepy/tweepy#448] opened 2014-06-13 05:07 UTC
This error occurs when there is a high stream of tweets in a particular time.. Example try streaming world cup hashtag during the game. The problem looks similar to this https://dev.twitter.com/discussions/9554 Can anyone help in fixing this?

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 173, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 220, in _read_loop
    d = resp.read(1)
  File "/usr/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 586, in _read_chunked
    raise IncompleteRead(''.join(value))

**Comment by Harmon758** [comment] 2019-04-26 22:50
Marking as a duplicate of #237, but keeping this open until it's resolved, due to the relevant conversation in this thread.

**Comment by finiteautomata** [comment] 2020-04-09 17:58
Is there any update on this? I tried pushing everything to a consumer-producer scheme (using `queue` module) to avoid doing heavy-processing on the listener with no success :disappointed:

**Closed** 2021-01-19 09:43 UTC
Labels: Bug, Duplicate

**Comment by Harmon758** [comment] 2021-01-19 10:09
This should now be resolved with https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f by simply handling it as a connection error and attempting to reconnect.

It might be worth mentioning this behavior (of Tweepy automatically attempting to reconnect when this connection error occurs due to Twitter's API disconnecting the stream for falling too behind) in the documentation for streaming. I plan on improving the documentation for streaming at some point in the future, so if it hasn't been added to the documentation by then, I'll probably mention that Tweepy automatically attempts to reconnect when connection errors occur and note the `StreamListener` method that's called when that happens, as well as include this along with other reasons for connection errors.

@jamesfebin 
For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.

@rthijssen `stall_warnings` has been added as a parameter for `Stream.sample` with #701 (https://github.com/tweepy/tweepy/commit/bc3bbc198b457a8006322c064f1efa9827b6ad7c) now as part of v3.6.0 and newer.
