### ISSUE TITLE
Twitter removing free access to API on February 9th

### ISSUE THREAD

**Issue by kevinggrimm** [tweepy/tweepy#2061] opened 2023-02-03 16:38 UTC
Article here: https://www.theverge.com/2023/2/2/23582615/twitter-removing-free-api-developer-apps-price-announcement

Maybe this has already been discussed but wanted to see if there's an effort underway to add support for the paid API version if/when that rolls out. I haven't looked for updates to their docs so could be that there is limited information at this time - either way wanted to flag.

**Comment by Harmon758** [comment] 2023-02-03 17:05
Duplicate of #2058

**Closed by Harmon758** 2023-02-03 17:05 UTC
