### ISSUE TITLE
Tweet.py search method does not support pagination

### ISSUE THREAD

**Issue by henritapanisalonen** [tweepy/tweepy#1040] opened 2018-05-05 04:22 UTC
I'm trying to create a program that would create a list of the twitter handles that a given twitter-handle follows and write those handles into a txt-document. So people/accounts that a certain "handle" follows. When I run the program, I keep getting this error: Tweet.py search method does not support pagination

Can anyone help? 

````
import tweepy
import csv
import time

from keys import keys

screen_name = keys['screen_name']
consumer_key = keys['consumer_key']
consumer_secret = keys['consumer_secret']
access_token = keys['access_token']
access_token_secret = keys['access_token_secret']

username = input("Give me a Twitter handle: ")
user = username

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

public_tweets = api.home_timeline()

user = username
user = api.get_user(user)

outfilename = "norwayun.txt"
outfile = open(outfilename, "w", encoding = "utf-8")


print("\n")
print("Users Twitter name: ",user.screen_name)
print("Users follower count: ",user.followers_count)
print("Users friends count: ", user.friends_count)
print("Users usual location: ", user.location)
print("Users tweets: ", user.statuses_count)
# add friend in users friends to a list and write that list into a txt document
for friend in tweepy.Cursor(user.friends).items():
    print(friend.screen_name)
    outfile.write(friend.screen_name)



print("\n")


`

**Comment by Harmon758** [comment] 2019-04-25 06:49
The error you should be seeing is `tweepy.error.TweepError: This method does not perform pagination`.

This is caused by the line `for friend in tweepy.Cursor(user.friends).items():` and is because `User.friends`is a shortcut for `API.friends`:
https://github.com/tweepy/tweepy/blob/d240f2083ae1f47f6e6a3c047042ae8eadc0f925/tweepy/models.py#L170-L171 However, `Cursor` assumes the method passed is itself a bound API method and checks for the `pagination_mode` attribute:
https://github.com/tweepy/tweepy/blob/d240f2083ae1f47f6e6a3c047042ae8eadc0f925/tweepy/cursor.py#L11-L25 Since you're passing the shortcut method, that doesn't exist and an error is raised.

This should easily be resolved by simply using `API.friends` directly, e.g.:
`for friend in tweepy.Cursor(api.friends, user_id=user.id).items():`

**Closed by Harmon758** 2019-04-25 06:49 UTC
