### ISSUE TITLE
Retreive tweet full text when tweet_mode is extended

### ISSUE THREAD

**Issue by ahuei123456** [tweepy/tweepy#878] opened 2017-04-18 03:30 UTC
When `tweet_mode` is `extended` twitter api returns full text in `full_text` field instead of `text`. 

https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by miketheman** [comment] 2017-07-07 11:20
The query api will currently allow passing the param to change the returned payload, but the Status result doesn't know how to retrieve the `full_text` field.

```python
new_tweets = client.user_timeline(screen_name=screen_name,
                                      count=200, tweet_mode='extended')
```

```
In [53]: new_tweets[0].full_text is None
Out[53]: False

In [54]: new_tweets[0].text is None
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-54-cff90907e218> in <module>()
----> 1 new_tweets[0].text is None

AttributeError: 'Status' object has no attribute 'text'
```

**Comment by victorpenna** [comment] 2017-09-26 13:58
I was finding a similar mistake. However I solved my problem, tweet mode = 'extended', only works with tweet.full_text mode.
In the normal method, it will generate the described error.

**Comment by Dmon1Unlimited** [comment] 2017-10-14 15:51
@victorpenna  hey, could you elaborate on your answer? :) i'm a bit new to this

**Comment by victorpenna** [comment] 2017-10-17 11:09
has no error, just use do as it says in the documentation. If you are going to use some extra condition, then just use the extra parameters within the condition.

Example:
```
results = api.search(q=query, lang=language, count=tweetCount, tweet_mode='extended')
print(tweet.fulltext)
```
In the above case, I will print according to the arguments, the full mode tweets. But first let me know that I want the tweets in full mode!

**Comment by Rsavreux** [comment] 2017-11-21 12:00
@victorpenna , I believe tweet.fulltext will generate an error, full_text to be used:

```
results = api.search(q=query, lang=language, count=tweetCount, tweet_mode='extended')
for tweet in results:
        print(tweet.full_text)```

**Comment by spacejunkjim** [comment] 2017-12-24 19:35
How can I do this with the streaming API?

**Comment by jemshit** [comment] 2018-01-03 20:24
does not work for user_timeline

**Comment by jaycech3n** [comment] 2018-01-30 00:19
@spacejunkjim See https://github.com/tweepy/tweepy/issues/935#issuecomment-361416826

**Comment by hugoncosta** [comment] 2018-06-29 11:34
This doesn't work when the tweet is a retweet. You're forced to make a structure with try/except to look for the full text in the retweet if exists otherwise get the "normal" full text

**Comment by pabblo1717** [comment] 2018-07-12 19:44
Es verdad el texto completo no aparece si es un retweet.....

**Comment by theAmouie** [comment] 2018-09-03 09:25
Apparently, tweet_mode='extended' doesn't work for retweets. What should I do to retreive full text of retweets?

**Comment by colditzjb** [comment] 2018-09-25 05:57
This seems to work for me - getting the most comprehensive text for both streaming and REST API endpoints.  I always connect to REST API with "tweet_mode='extended'", for sure. I think this covers all of the available places where tweet text resides (and gives preference to more comprehensive text)...

```
# This loads the most comprehensive text portion of the tweet  
def parseText(data):       
    # Try for extended text of original tweet, if RT'd (streamer)
    try: text = data['retweeted_status']['extended_tweet']['full_text']
    except: 
        # Try for extended text of an original tweet, if RT'd (REST API)
        try: text = data['retweeted_status']['full_text']
        except:
            # Try for extended text of an original tweet (streamer)
            try: text = data['extended_tweet']['full_text']
            except:
                # Try for extended text of an original tweet (REST API)
                try: text = data['full_text']
                except:
                    # Try for basic text of original tweet if RT'd 
                    try: text = data['retweeted_status']['text']
                    except:
                        # Try for basic text of an original tweet
                        try: text = data['text']
                        except: 
                            # Nothing left to check for
                            text = ''

    text = str(text.encode('unicode-escape'))[2:-1]
    return text
```

**Comment by progfa** [comment] 2018-10-07 22:53
That worked and explained this for me using twython. Tnx!

**Comment by roshan1532** [comment] 2019-02-21 17:22
> This seems to work for me - getting the most comprehensive text for both streaming and REST API endpoints. I always connect to REST API with "tweet_mode='extended'", for sure. I think this covers all of the available places where tweet text resides (and gives preference to more comprehensive text)...
> 
> ```
> # This loads the most comprehensive text portion of the tweet  
> # Where "data" is an individual tweet, treated as JSON / dict
> def getText(data):       
>     # Try for extended text of original tweet, if RT'd (streamer)
>     try: text = data['retweeted_status']['extended_tweet']['full_text']
>     except: 
>         # Try for extended text of an original tweet, if RT'd (REST API)
>         try: text = data['retweeted_status']['full_text']
>         except:
>             # Try for extended text of an original tweet (streamer)
>             try: text = data['extended_tweet']['full_text']
>             except:
>                 # Try for extended text of an original tweet (REST API)
>                 try: text = data['full_text']
>                 except:
>                     # Try for basic text of original tweet if RT'd 
>                     try: text = data['retweeted_status']['text']
>                     except:
>                         # Try for basic text of an original tweet
>                         try: text = data['text']
>                         except: 
>                             # Nothing left to check for
>                             text = ''
>     return text
> ```
> _Edit:_ Doh! I just realized that I'm posting in a Tweepy thread, but I'm currently using Twython in my implementation. I've used both Tweepy and Twython and they are fairly comparable Twitter API wrappers, so this code should still work (i.e., the Twitter API returns data in the same general format). Sorry for any confusion that this may cause, but I hope it might still help others who are trying to troubleshoot their code.

thank you so much it worked for me

**Comment by JBDemouy** [comment] 2019-02-28 22:08
Hey guys,

I'm still experiencing trouble. 
I must do something wrong since I'm pretty novice. 
When I had the def getText(...) to my script, nothing happens. Otherwise, with my script and without the retweet section problem, everything works great.
Can you help ? Sorry if I seem stupid but I'm not a python veteran...
Here's my script :

`onCherche = input("qué!? ")

tweets = t.GetSearch(term = onCherche,count = 500,result_type = "recent",return_json = True)

# print(json.dumps(tweets, indent=2, sort_keys=True))
# print("*"*60)

for tweet in tweets["statuses"]:
	s = []
# This is here that trouble begins. I'm not sure where to put it actually...
	def getText(tweet):
		try: text = tweet["retweeted_status"]["full_text"]
		except:

# Here, it's supposed to have an indent but I tried every possible indent and still nothing.
		s.append(tweet["created_at"])
		s.append(tweet["full_text"])
		s.append(tweet["user"]["name"])
		s.append(tweet["id"])
		s.append(tweet["retweet_count"])
		s.append(tweet["favorite_count"])
		s.append(tweet["lang"])
		s.append(tweet["user"]["location"])

		print("Date/Heure: ", tweet["created_at"])
		print("tweet: ", tweet["full_text"])
		print("Pseudo: ", tweet["user"]["name"])
		print("IdUser: ", tweet["id"])
		print("Retweets: ", tweet["retweet_count"])
		print("P'tits coeurs: ", tweet["favorite_count"])
		print("Language: ", tweet["lang"])
		print("Location: ", tweet["user"]["location"])

		print("*"*80)`

Thanks a lot guys.
JB

**Comment by colditzjb** [comment] 2019-02-28 23:11
1. Add the _getText_ function to your code exactly as I wrote it above - don't try to take pieces of it or remove lines from it. You might still need to fix indent spacing, depending on how the rest of your code is indented (I use 4 spaces per indent level, but it looks like you're using 1 tab per indent level).
2. Where you want to use the tweet text, try calling `getText(tweet)` instead of `tweet["full_text"]`.

For example, this line:
```
	print("tweet: ", tweet["full_text"])
```

...would look like this:
```
	print("tweet: ", getText(tweet))
```

I hope this helps!

**Comment by machine-uprising** [comment] 2019-03-01 15:07
Another way to run a search and retrieve for text or full_text is using a dot notation type search. With it you can specify a series of paths to search through in a JSON object (or dictionary), check if the path exists and return the value of the path. It achieves the same result as a group of try:...except... statements but is more compact and reusable in your code. 

Below is my function and usage example to search a tweet record for text or full_text in the same pathways as the above getText() function. 

```python
import functools

def dotnot_pathfinder(path,obj):
    """ dotnot_pathfinder receives a path parameter either as a 
    dot notation string or a list of key values and returns the 
    value at that key if a value exists.
    :parameters
        path: dot notation string or list keys
        obj: dictionary object to be searched
    :returns
        value of the path or None if path is not found 
    """
    if isinstance(path,str):
        path = path.split('.')
    elif not isinstance(path,list):
        raise Exception("path must be dot-notated string or list object")
        
    try:
        return functools.reduce(lambda o, key: o.get(key) if o else None, path, obj)
    except AttributeError:
        return None

# Add your API keys to API_KEY, API_SECRET, ACCESS_TOKEN, ACCESS_SECRET
auth = OAuthHandler(API_KEY, API_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)
api = tweepy.API(auth_handler=auth)

tweet = api.get_status(id='1101424132774875137', tweet_mode='extended')
tweet = tweet._json

# Define the paths you want to search through. 
# You can either use dot notation or list objects
# Example: 'retweeted_status.full_text' or ['retweeted_status','full_text']
search_paths = [
    'retweeted_status.extended_tweet.full_text',
    'retweeted_status.full_text',
    'extended_tweet.full_text',
    'full_text',
    'retweeted_status.text',
    'text'
]

path_found, tweet_text = '',''
for dot_path in search_paths:
    tweet_text = dotnot_pathfinder(dot_path,tweet)
    if tweet_text is not None:
        path_found,tweet_text = dot_path, tweet_text
        break

print("DotNot Path--> %s"%path_found)
print("Tweet Text--> %s"%tweet_text)
```

You can also use this for other deep paths such as getting the user screen_name of the user from the retweeted_status. The pathway would be - 'retweeted_status.user.screen_name'

So you would use the function like:
```python
rt_user_screen_name = 'retweeted_status.user.screen_name'
# or as a list ['retweeted_status','user','screen_name']
user_screen_name = dotnot_pathfinder(rt_user_screen_name,tweet)
```

Hope you find this useful.

**Comment by JBDemouy** [comment] 2019-03-03 13:58
Hey guys !!
Thank you so much for taking the time to answer. 
So I copied the defText above my for tweet in tweets and changed my print text and everything seems to work perfectly. 
Last question, When I used my own script, I had an RT to tell me when it was a retweet but now I don't. Is it normal ? 

Again, thank you both for your answers. 
JB

**Comment by machine-uprising** [comment] 2019-03-03 15:40
@JBDemouy it depends which text object your are using from the tweet. If you are using the ['retweeted_status']['text'/'full_text'] it would not show the 'RT' at the beginning of the text. Maybe it would show if it was a retweet of a retweet but I haven't checked that scenario. 

If you get the text/full_text from the tweet you searched for it will have 'RT' at the beginning of the text.

**Comment by colditzjb** [comment] 2019-04-17 01:03
@JBDemouy That is correct. When we pull the text from the RT (i.e., ['retweeted_status']...), the "RT" prefix will not be included. That was by design in the _getText_ function, because I wanted to preserve the exact text of the tweet and not include the additional "RT ", which wouldn't appear in the native tweet format on Twitter. If you wanted to know if the tweet is a RT, you could include an additional check, to see if there is a ['retweeted_status'] field. Something like this might work... 

`if tweet['retweeted_status']: RT = True`

@machine-uprising I also wanted to note that I like that _dotnot_pathfinder_ function! That's definitely worthwhile when trying to capture additional data fields that may or may not be in the tweet (e.g., geolocation coordinates, quoted status, user mentions). AFAIK, there is no way to determine if a tweet is a RT of a RT, as the Twitter API doesn't preserve that information. Here's a helpful guide to how Twitter API nests RTs, mentions, etc. https://gwu-libraries.github.io/sfm-ui/posts/2016-11-10-twitter-interaction

**Comment by Harmon758** [comment] 2019-07-31 02:23
`tweet_mode` can already be passed as a keyword-argument parameter for any API method that uses an endpoint that accepts that parameter, and the `full_text` field will be an attribute of the resulting Status object. There were only a few methods that required minor changes to handle the parameter.

I've added [a section in the documentation that covers extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html) in general to supplement [Twitter’s Tweet updates documentation](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).
@Dmon1Unlimited @jamesrashford @hugoncosta @pabblo1717 @theAmouie 

@miketheman As you've shown, `full_text` is properly added as an attribute for the Status object.
`text` is not an attribute of Status objects in extended mode, as it is replaced by the `full_text` attribute. This is reflective of the attributes Twitter's API provides.

@hugoncosta You can check for the existence of the attribute beforehand as well, rather than handling the exception that occurs when the attribute doesn't exist.

@colditzjb Not only is this try . . . except chain with inline try blocks and usage of blanket exception handlers atrocious coding style and design, but you're assigning to a variable that's never used instead of just directing returning it. You're also mixing handling of Tweets from REST APIs and Streaming APIs and inefficiently trying to access the `retweeted_status` field multiple times in the case that it doesn't exist.

@JBDemouy It's difficult to determine what the issue is with your original script, as you don't provide any information like a traceback or what you expect to happen, and it's hard to tell from your formatting, but you don't seem to use your `getText` method anywhere.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

@colditzjb @JBDemouy 
> If you wanted to know if the tweet is a RT, you could include an additional check, to see if there is a ['retweeted_status'] field. Something like this might work...
> 
> `if tweet['retweeted_status']: RT = True`

This will raise an `AttributeError` in the case that the Tweet is a Retweet and the `retweeted_status` field does not exist. Instead, you can simply check `"retweeted_status" in tweet` or if `tweet` is a Status object, `hasattr(tweet, "retweeted_status")`.

@machine-uprising While something like this might be useful when processing more complex data, this is overly complicated and inefficient for this use case, where you could use [a single `if hasattr` check](https://tweepy.readthedocs.io/en/latest/extended_tweets.html#examples) or try . . . except block instead.

**Closed by Harmon758** 2019-07-31 02:23 UTC

**Comment by colditzjb** [comment] 2019-07-31 16:32
@Harmon758 Way to show up more than two years later, insult a novice contributor, mark a functional work-around as off-topic, and not offer a novice-friendly alternative. 

> @colditzjb Not only is this try . . . except chain with inline try blocks and usage of blanket exception handlers atrocious coding style and design, but you're assigning to a variable that's never used instead of just directing returning it. You're also mixing handling of Tweets from REST APIs and Streaming APIs and inefficiently trying to access the retweeted_status field multiple times in the case that it doesn't exist.

...despite [that code](https://github.com/tweepy/tweepy/issues/878#issuecomment-424216624) actually working flawlessly under many use cases (i.e., REST API, streaming API) and having multiple likes and positive responses from others who also who got it to work. This wasn't submitted as a shining example of "best coding practice" or "most Pythonic". It is a broad work-around for others who wander into this page looking for something that can be quickly snipped. 

Save your coding style and design pedantics for StackOverflow, and go ahead and mark this response as off-topic in 3, 2, 1...

**Comment by Harmon758** [comment] 2019-07-31 20:39
> Way to show up more than two years later

I've only recently started maintaining the library and only yesterday wrote up the documentation for extended Tweets. Hence my response here after doing so. Your last response was a few months ago though, hardly an issue that's been inactive for two years.

> insult a novice contributor

Nowhere did I intend to insult you; I was simply critiquing your code. If you can't take constructive criticism about your code and use that to improve it, you're going to stay a novice. That's not an insult, just my honest analysis.

> mark a functional work-around as off-topic

The main reason I marked it as off-topic is because you yourself said it was intended to be used with a different library, which is off-topic from this issue with this library. It does work with raw Tweet data, but not with the Status object this library uses as a model. Additionally, you're offering it as a solution to be copy and pasted and trying to spoonfeed it to other people when it is not a good example of how to handle extended Tweets.

> not offer a novice-friendly alternative

If anything, I think the [examples](https://tweepy.readthedocs.io/en/latest/extended_tweets.html#examples) that I've added to the documentation are much clearer than a try . . . except chain. They're also provided with context to explain their functionality. Regardless, if anyone has a question about them, they're free to ask.

> despite [that code](https://github.com/tweepy/tweepy/issues/878#issuecomment-424216624) actually working flawlessly under many use cases (i.e., REST API, streaming API)

I've specifically pointed out the flaws in what you've quoted, including exactly the fact that you're mixing handling of two separate and different use cases. This reduces the efficiency, clarity, and maintainability of the code.

> having multiple likes and positive responses from others who also who got it to work

There is a difference between code that works and code that is written well. You could make your function 100 lines longer to do the same thing and there would likely still be people who would be willing to copy and paste it without understanding what it does and thank you for it.

> This wasn't submitted as a shining example of "best coding practice" or "most Pythonic". It is a broad work-around for others who wander into this page looking for something that can be quickly snipped.

That's just it; you *are* offering it as an example and encouraging others to copy and paste it.
There's no reason for you not to continue to use that code in your own personal project if you don't care about its performance or clarity and it serves its purpose, but if you're advocating proliferation of the code, then it should be written as well as possible. Even before I added examples to the documentation and before you commented with that code, there were other better written examples (e.g. https://github.com/tweepy/tweepy/issues/935#issuecomment-375933277, https://github.com/tweepy/tweepy/issues/935#issuecomment-383603183) in an issue that's already been linked here.

> Save your coding style and design pedantics for StackOverflow

They're not pedantics (I'm also going to ironically point out that this isn't a word as pedantic is an adjective, not a noun, but w/e, I know what you mean) when the performance and maintainability of the code is in question. I'm also not sure why you're trying to discredit StackOverflow. I myself find the site very useful, and I'm sure many others do too.

> go ahead and mark this response as off-topic in 3, 2, 1...

Regardless of this passive-aggressive remark, I'm going to do so, as well as marking this, my own comment here as off-topic, because they *are off-topic*. I'm also not going to respond to any further discussion about this unless it pertains specifically to this issue.

**Comment by okomarov** [comment] 2019-07-31 22:07
@Harmon758 Just know that I appreciate and learn from your work in mantaining this project. I am sure I am not the only one.

**Comment by colditzjb** [comment] 2019-08-01 01:07
@Harmon758 - Yes, I absolutely took your response personally - directly calling me out for "**atrocious** coding style and design" (emphasis added for clarity) isn't what I would consider "constructive criticism about [my] code" and I of course felt a bit chaffed. My passive-aggressive response was an artifact of that, though I do regret and apologize stoking your fire about this issue; I've wasted both your time and mine. 

> I'm also not sure why you're trying to discredit StackOverflow. I myself find the site very useful, and I'm sure many others do too.

No discredit was intended or implied. StackOverflow is an incredibly helpful site where I would expect to receive this type of direct and pointed feedback about my coding _style_. Aside from my misgivings about your tone, your feedback was otherwise helpful for my learning - so thank you for taking the time to respond to me here. Thank you also for adding context and improving the code documentation. Your continued work on this repo is definitely appreciated. 

PS. Solid catch on the irony of calling me out on "pedantics". That's totally not a word, but it's pedantic of you to say so. ;-)

**Comment by mansi-aggarwal-2504** [comment] 2020-02-27 12:32
I am using the tweed_mode in Premium full-archive API. But I am getting this error:

{
    "error": {
        "message": "There were errors processing your request: Unknown parameter:'tweet_mode'"
        "sent": "2020-02-27T12:23:22+00:00",
        "transactionId": "XXXX"
    }
}
My request:
https://api.twitter.com/1.1/tweets/search/fullarchive/floodrescue123.json?query=keyword&tweet_mode=extended

**Comment by Harmon758** [comment] 2020-02-27 15:28
Please stop necro-bumping closed issues with this comment.
Premium APIs do not accept a `tweet_mode` parameter, but rather provide an `extended_tweet` field in the response. As already referenced here, see [Twitter's Tweet updates documentation](https://developer.twitter.com/en/docs/tweets/tweet-updates) and [Tweepy's Extended Tweets documentation](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).

**Comment by coderdev27** [comment] 2023-03-24 14:10
> Apparently, tweet_mode='extended' doesn't work for retweets. What should I do to retreive full text of retweets?

expansions=referenced_tweets.id 
use this

**Comment by Harmon758** [comment] 2023-03-24 16:03
Please don't necro-bump old closed issues.
This issue was about Twitter API v1.1, not v2.
