### ISSUE TITLE
Additional support needed to fix unreliable response for Twitter API v2 pagination interface

### ISSUE THREAD

**Issue by askayastha** [tweepy/tweepy#1550] opened 2021-03-20 02:01 UTC
I just tested @Harmon758 's recently pushed Paginator class in the api-v2 branch for my Twitter API v2 scraper. The interface works like a charm. The only issue is that Twitter API v2 pagination is very unreliable sometimes and returns no results for a valid "next_token". However, sending the request again returns the data. I have noticed this issue quite often when testing the v2 APIs in the Postman app as well in my scraper. Currently, I am using retry logic to get around this issue. It would be great if you could add support for handling this particular issue.

Thanks!

**Comment by Harmon758** [comment] 2021-03-20 03:57
Thanks for testing out the branch / PR #1535 and for the feedback.
Do you have a reproducible example (MCVE/SSCCE) of this happening? or an acknowledgement by Twitter staff or discussion of this bug, e.g. on the [Twitter Developers Forums](https://twittercommunity.com/)?

**Comment by askayastha** [comment] 2021-03-20 05:14
No, I don't have an acknowledgment by Twitter staff or discussion of this issue. It looks like a bug in their API, which I will report to them. I am not particularly familiar with the type of reproducible example you are looking for. However, I can tell you how to reproduce that particular issue. If you send a user tweet timeline request for a maximum of 3200 tweets for "elonmusk" with your Paginator interface, you will not be able to retrieve all the tweets.

**This code will be the showstopper as you can imagine.**

"""Stop the iteration here if no more data is returned."""
if response.data is None:
.... raise StopIteration

Please see the two attached files scraped from Twitter using Tweepy's api-v2 branch (in addition to my retry logic).
- twitter_dump_with_retry_logic.xlsx (3200 tweets)
- twitter_dump_without_retry_logic.xlsx (<3200 tweets)
[twitter_dump_with_retry_logic.xlsx](https://github.com/tweepy/tweepy/files/6174943/twitter_dump_with_retry_logic.xlsx)
[twitter_dump_without_retry_logic.xlsx](https://github.com/tweepy/tweepy/files/6174944/twitter_dump_without_retry_logic.xlsx)

**Comment by Harmon758** [comment] 2021-03-21 03:19
Does this happen with any other account besides "elonmusk"?
This could be an eventual consistency issue for that account:
https://twittercommunity.com/t/inconsistent-tweet-retrieval/150635

**Comment by askayastha** [comment] 2021-03-23 04:47
I tried to replicate the issue for other highly followed Twitter accounts but couldn't. It seems to only affect the "elonmusk" account.

**Comment by klyondx** [comment] 2021-06-06 13:38
Hi there, I too can confirm this seems to be Twitter v2 API specific with the `@elonmusk` account. My search for a similar error on a separate js project took me here. My solution was similar too - retry and hope for the best...

**Comment by Harmon758** [comment] 2021-06-06 14:47
I reached out to a Twitter staff member about this in March, but have yet to hear back about it.
There have also been additional forum posts without any satisfactory answers or follow-up (e.g. https://twittercommunity.com/t/incosistent-data-retrieval/153006, https://twittercommunity.com/t/inconsistent-retrieval/154417, https://twittercommunity.com/t/inconsistent-retrieval/154937).

Since this seems to be an eventual consistency issue with Twitter's API for this specific account and there's precedent for this happening (see #1361 and https://twittercommunity.com/t/user-timeline-returning-unexpected-results/130885), I'm going to close this for now. Tweepy itself shouldn't be handling this edge case. You could make another Twitter Developers forum post for more visibility, but there's likely not much to be done about it.

**Closed by Harmon758** 2021-06-06 14:47 UTC
Labels: API, Need Follow-Up
