### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by Peteous** [tweepy/tweepy#847] opened 2017-02-21 20:04 UTC
Your documentation doesn't do a good job of explaining what is contained by each object type, both methods and variables. In particular, the `Status` object is something I can't find reference to anywhere.

**Comment by Cin316** [comment] 2017-05-13 03:09
I second this.  I can't find any documentation on all of the objects the API methods return.  What fields and methods does the `User` class have?  Is this documented anywhere?

**Comment by fitnr** [comment] 2017-05-13 19:45
The Twitter API docs are a great source of information over and above Tweepy's somewhat limited docs. The attributes and methods of the objects follow the Twitter API pretty closely. For instance, a `Status` object contains attributes for most or all of the top-level keys in a twitter Status object (see this [example response](https://dev.twitter.com/rest/reference/get/statuses/show/id)).

Running `help(foo)` and/or `dir(foo)` in the Python console is also a great way to get a information about an objects methods and attributes.

**Comment by Harmon758** [comment] 2019-04-30 00:44
Duplicate of #720

**Closed by Harmon758** 2019-04-30 00:44 UTC
