### ISSUE TITLE
I can't get replies to to work

### ISSUE THREAD

**Issue by ogierm** [tweepy/tweepy#1241] opened 2019-07-12 22:10 UTC
**I want to create a thread,** 
however every single status is being pushed onto my profile seperately.
Twitter does recognize the screen name and mentions the user. The tweet is being displayed properly otherwise. The tweet IDs check out too.

This is the responsible snippet.
`user` is a `User` object, `previous_tweet` is a status
```python
tweet = api.update_status("@" + user.screen_name + " " + f.read(), in_repy_to_status_id=previous_tweet.id_str)
```
I've also tried `.id` instead of `.id_str`, but that didn't help either.
Additionally I've added a delay of 10 seconds between the `previous_tweet` and this tweet, just to make sure everything is registered at Twitter.

**Comment by Harmon758** [comment] 2019-07-12 22:56
I'm unable to reproduce this issue.
Using either the `id` or `id_str` attribute both work, and the new Tweet is a reply to the specified Tweet.
Is `user` the author of `previous_tweet`? e.g. `previous_tweet.user.screen_name` should work.
If so, can you provide a reproducible example of what you're trying?

**Comment by ogierm** [comment] 2019-07-14 13:03
Yes,`user` is the author of `previous_tweet`.

I've got it to work in a simpler example and will now try to figure out what I got wrong in my og code.

```python
import tweepy
import secrets

auth = tweepy.OAuthHandler(secrets.consumer_key, secrets.consumer_secret)
auth.set_access_token(secrets.access_token, secrets.access_token_secret)
api = tweepy.API(auth)

tweet = api.update_status("my name jeff")
api.update_status("@" + tweet.user.screen_name + " lol", in_reply_to_status_id=tweet.id)
```
![image](https://user-images.githubusercontent.com/29630575/61183985-7d351e00-a648-11e9-890d-0269d9abad27.png)

**Comment by ogierm** [comment] 2019-07-14 13:28
No - I just can't seem to get it to work...

**Comment by Harmon758** [comment] 2019-07-14 18:05
I'm going to close this since it seems to be an issue with your code rather than the library.
Feel free to provide your code, either here or in [the official Discord server](https://discord.gg/bJvqnhg), if you want help debugging it.

**Closed by Harmon758** 2019-07-14 18:05 UTC
Labels: Need Follow-Up, No Reproduction

**Comment by FBosler** [comment] 2019-09-07 18:06
I have the same issue.
It works perfectly when replying to my own tweets, but as of now, I've not managed to reply to somebody else's Tweets.
It is exactly what ogierm describes, the tweet will be pushed out and be visible on my profile under "Tweets & replies" but It will not show up when actually checking the original tweet.

**Comment by Harmon758** [comment] 2019-09-17 23:44
I'm still unable to reproduce this.
Something like `api.update_status("@Twitter Test Tweet", in_reply_to_status_id=1173652184405352449)` works for me.

You need to provide a reproducible example (MCVE/SSCCE) of what you're trying, so that the issue can be pinpointed, not the other way around.

**Comment by kudeiro** [comment] 2020-02-08 16:50
I have this issue too, exactly as described by "FBosler"

**Comment by maxis321** [comment] 2020-08-18 06:56
For me the reply seems to appear not in the thread but as a separate tweet. Any ideas why ?
