### ISSUE TITLE
[streaming.py file:RuntimeError: No active exception to reraise]

### ISSUE THREAD

**Issue by varunkumarmnnit** [tweepy/tweepy#601] opened 2015-04-27 04:43 UTC
I am using tweepy for one of my project and following issue is coming :+1: raceback (most recent call last):
  File "C:/Users/Wilson/PycharmProjects/Avalon/Twitter.py", line 95, in <module>
    stream.filter(track=['gay', 'bitch', 'slut', 'whore'], languages=["en"])
  File "C:\Python34\lib\site-packages\tweepy\streaming.py", line 428, in filter
    self._start(async)
  File "C:\Python34\lib\site-packages\tweepy\streaming.py", line 346, in _start
    self._run()
  File "C:\Python34\lib\site-packages\tweepy\streaming.py", line 286, in _run
    raise
RuntimeError: No active exception to reraise

.I found many people have found this problem and they have reported the solution also but still in the final code on github the fix has not been implemented .

**Comment by tehspaceg** [comment] 2015-04-27 19:44
This is a duplicate of #570. I suggest you close this one out and comment on that.

**Comment by Harmon758** [comment] 2019-04-27 02:03
This should now be fixed with https://github.com/tweepy/tweepy/commit/37e318befb56f84fe8ed4f0999210e3c5d9266f6, which was released as part of Tweepy v3.6.0.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Closed by Harmon758** 2019-04-27 02:03 UTC
