### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by khairidaday** [tweepy/tweepy#912] opened 2017-07-26 17:39 UTC
how about this error: 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\khairy\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\khairy\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\khairy\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy-3.6.0-py3.5.egg\tweepy\streaming.py", line 297, in _run
    six.reraise(*exc_info)
  File "C:\Users\khairy\AppData\Local\Programs\Python\Python35\lib\site-packages\six-1.10.0-py3.5.egg\six.py", line 686, in reraise
    raise value
  File "C:\Users\khairy\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy-3.6.0-py3.5.egg\tweepy\streaming.py", line 266, in _run
    self._read_loop(resp)
  File "C:\Users\khairy\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy-3.6.0-py3.5.egg\tweepy\streaming.py", line 323, in _read_loop
    raise TweepError('Expecting length, unexpected value found')
tweepy.error.TweepError: Expecting length, unexpected value found

**Comment by Harmon758** [comment] 2019-05-01 04:18
Duplicate of #892 

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Closed by Harmon758** 2019-05-01 04:18 UTC
