### ISSUE TITLE
Calls to rate_limit_status count against the rate limit

### ISSUE THREAD

**Issue by AndersonHappens** [tweepy/tweepy#1258] opened 2019-08-17 00:57 UTC
Unlike what http://docs.tweepy.org/en/latest/api.html#API.rate_limit_status says (`Calls to rate_limit_status do not count against the rate limit`), calls to rate_limit_status count against the rate limit status because that is rate limited by [Twitter](https://developer.twitter.com/en/docs/developer-utilities/rate-limit-status/api-reference/get-application-rate_limit_status.html). You can   [see here where tweepy calls the twitter method in the code](https://github.com/tweepy/tweepy/blob/c4839adc7b9b0507ed4b7c5404f76bda8e6f51dd/tweepy/api.py#L612). I think that we need to either start tracking the rate limit separately or change the documentation.

**Comment by Harmon758** [comment] 2019-08-17 01:00
Duplicate of #1133

**Closed by Harmon758** 2019-08-17 01:00 UTC
