### ISSUE TITLE
'with_media' is deprecated will Tweepy support the new method?

### ISSUE THREAD

**Issue by phylaxis** [tweepy/tweepy#643] opened 2015-08-29 00:16 UTC
According to Twitter the [update_with_media](https://dev.twitter.com/rest/reference/post/statuses/update_with_media) endpoint is deprecated. Are there plans to update Tweepy to support the `POST statuses/update` method? I see the `API.update_status` already supports passing in of media_ids, so can I assume this is something that is in the works?

**Comment by phylaxis** [comment] 2015-08-29 20:34
OK. I did some more digging and I see that the `media_upload` method and support was added in as part of 460acae6287ad8e566a053db98089fa273bfb86d, but looks like there is not updated documentation. Would be helpful if you could update that.

In case it might help others here is how I implemented it in my Google App Engine project:

```
upload = api.media_upload(filename=filename, file=file)
media_ids = [upload.media_id_string]
result = api.update_status(media_ids, status=msg[:140])
```

**Comment by lucabezerra** [comment] 2017-02-15 16:18
Thanks for the tip!
Just thought I should mention, I had to add the keyword `media_ids=` before the first parameter, or else I'd get a "Multiple values for parameter status supplied!" error. Also, I've removed the `file=file` parameter, as it was doing nothing for me :)

**Comment by aleontiev-sf** [comment] 2018-01-05 19:11
Yes; this is a very helpful tip, although I had to tweak the code snippet above, to avoid an error.  Specifically, the third statement caused the following error for me:  'dict' object has no attribute 'media_id_string'. 

Changing this statement to 'media_ids = [upload['media_id_string']]' fixed the error and I was able to upload an image as a Tweet.

**Comment by Harmon758** [comment] 2019-05-06 01:05
Duplicate of #541.
As you noted, [`API.media_upload`](https://tweepy.readthedocs.io/en/latest/api.html#API.media_upload) was already added with https://github.com/tweepy/tweepy/commit/460acae6287ad8e566a053db98089fa273bfb86d (#542).
Documentation for the method has now been added https://github.com/tweepy/tweepy/commit/805ed5c7a43e391a2b92b92887e0eae0c1545841 (#1028) as part of Tweepy 3.7.0.

**Closed by Harmon758** 2019-05-06 01:05 UTC
