### ISSUE TITLE
Twitter changes for more than 140 characters

### ISSUE THREAD

**Issue by robertdenton** [tweepy/tweepy#737] opened 2016-05-24 18:14 UTC
All I know is what the [blog post](https://blog.twitter.com/2016/doing-more-with-140-characters) says. Here's an excerpt:

> Today, we’re excited to announce an upcoming set of changes rolling out over the coming months to enable people to express even more within 140 characters.
> ...
> Our goal is to give developers and partners this advance notice of changes to the format of Tweets so that they can prepare their products and applications appropriately.

Just wanted to file an issue to make sure y'all are aware and potentially provide a forum for discussion about what changes may be necessary.

**Comment by burndive** [comment] 2016-05-24 22:38
My read is that there will be a longer text attribute, with additional metadata fields to identify the "logical" prefix and suffix, in the form of character indices.  
It would be very useful for tweepy to supply the broken-down individual strings, but it looks like as soon the Twitter API change goes live, we will be able to parse the json to find the indices and determine what text fits in which of the three regions without any code changes to tweepy.

This is in keeping with their statement that backwards and forwards compatibility being their priority.

**Comment by burndive** [comment] 2016-05-26 23:23
Having enabled the 'extended' features in my scripts, the json is there and readable, but since text is missing when full_text is present, I can no longer rely on the Tweepy status.text attribute. 
Depending on whether you're using the Streaming or Rest APIs, and depending on whether the tweets are classic or extended, they are presented different ways in the json.  Tweepy needs to be updated to provide both a full_text and a text, as well as the display_text_range array of indices for every flavor of status.
There are also extended_entities and entities/extended_entities (depending on the mode and status type) that should be surfaced.

**Comment by burndive** [comment] 2016-05-31 18:05
Tweepy also needs support for the auto_populate_reply_metadata boolean parameter.

**Comment by kodeine** [comment] 2016-06-10 23:55
so is this ready? whats the param for full text?

**Comment by Mandrewoid** [comment] 2016-09-10 05:21
Hey I noticed an issue with this today while using the streaming API. I found a tweet that showed up as
"RT @hiwhit: Think of all the people who love & adore you locally, globally. Consider all the lives you've changed. Stop holding onto your uâ€¦"

And I thought that was very strange so I browed to the user's timeline in a browser, and the tweet was 
"RT @hiwhit: Think of all the people who love & adore you locally, globally. Consider all the lives you've changed. Stop holding onto your unworthiness."

The full text is 151 chars long. It looks like tweepy just mashed all the extra characters together.

**Comment by spdionis** [comment] 2016-09-13 08:45
I think this issue should get high priority. The api changes are coming on the 19th september.

source; http://www.theverge.com/2016/9/12/12891562/twitter-tweets-140-characters-expand-photos

**Comment by rosscg** [comment] 2017-07-20 15:30
I am getting the same result for text and full_text, both are truncated yet the truncated flag is False in both cases.

Command is:
statuses = api.user_timeline(**kwargs, count=50, trim_user=True, tweet_mode='extended')

**Comment by pau1a** [comment] 2017-11-21 19:02
Is this fixed?

**Comment by Nebelhom** [comment] 2017-12-05 22:31
Hi Everyone, in the same vein as pau1a. Is someone looking into a fix for this?

Thanks a lot :)

**Comment by burndive** [comment] 2017-12-05 22:45
Here's a version of the code I've been using to parse the text and full_text out of incoming tweets:
`def get_tweet_text_full_text_tuple(tweet, logVerbose=True):
    text = ""
    full_text = ""

    if "full_text" in tweet._json:
        if logVerbose:
            print("This tweet has full_text rather than text.", flush=True)
        full_text = tweet._json["full_text"]
        print("full_text: " + full_text.encode('ascii', 'replace').decode(), flush=True)
        if "display_text_range" in tweet._json:
            beginIndex = tweet._json["display_text_range"][0]
            endIndex   = tweet._json["display_text_range"][1]
            if logVerbose:
                print("Found display_text_range: " + "[" + str(beginIndex) + "," + str(endIndex) + "]")
            text = full_text[beginIndex:endIndex]
        else:
            text = full_text
    elif "extended_tweet" in tweet._json and "full_text" in tweet._json["extended_tweet"]:
        if logVerbose:
            print("This tweet has extended_tweet properties.", flush=True)
        full_text = tweet._json["extended_tweet"]["full_text"]
        if logVerbose:
            print("full_text: " + full_text.encode('ascii', 'replace').decode(), flush=True)
        if "display_text_range" in tweet._json["extended_tweet"]:
            beginIndex = tweet._json["extended_tweet"]["display_text_range"][0]
            endIndex   = tweet._json["extended_tweet"]["display_text_range"][1]
            text = full_text[beginIndex:endIndex]
            if logVerbose:
                print("Found display_text_range in extended_tweet: " + "[" + str(beginIndex) + "," + str(endIndex) + "]")
        else:
            text = full_text
    elif "text" in tweet._json:
        if logVerbose:
            print("This is a classic tweet. text is text", flush=True)
        text = tweet._json["text"]
        print("text: " + text, flush=True)
        full_text = text
    else:
        text = tweet.text
        full_text = text
        print("text: " + text, flush=True)

    return (text, full_text)
`

**Comment by Nebelhom** [comment] 2017-12-05 23:28
@burndive Thanks a lot for your input. The trouble I have is that no matter if I use extended_mode or not, I receive in both text and full_text the same string ending in "..."

e.g. [https://twitter.com/_backtable/status/937496756773941248](https://twitter.com/_backtable/status/937496756773941248) always shows as
``RT @_backtable: Oldie but goodie podcast Ep 3:  Tunneled Dialysis Catheters with @mcbreamy and @ABrandisVIR #IRad @SIRRFS @VanderbiltIr @SI…``

This is using ``api.user_timeline(..., twitter_mode='extended')`` (or without)

Any ideas on this? Thanks a lot. Please let me know if I need to raise a different issue for this.

Thanks :)

**Comment by burndive** [comment] 2017-12-06 00:12
@Nebelhom Yeah, I haven't been relying on Tweepy to parse out the full_text.  The status object has embedded json data, and I'm using that to create my own tuple of text and full_text.  

The tweet.full_text attribute is, as you described, useless.  My code above uses data found in the tweet._json structure.

**Comment by Nebelhom** [comment] 2017-12-06 10:12
@burndive Hi, in the end, your code did not give me the full text, but thanks to you, I have found the problem "in my case" ;) Thanks a lot for your help :)

Solution/conclusion:
All the tweets, that did not show fully were retweets. You can find the full text for those under ``tweet._json['retweeted_status']['full_text']``

I did not find a good flag just yet to check if it is a retweet (only flags I found checked if this tweet was retweeted), so I used the 'RT' at the beginning as a handle. If someone finds a better one, I am glad to listen. It would make the code simpler.

**Comment by burndive** [comment] 2017-12-06 17:18
@Nebelhom Good catch.  In my scripts I always disregard retweets.  The test I have to identify a retweet is actually the presence of the 'retweeted_status' element:

```
        if 'retweeted_status' in tweet._json:
            isRetweet = True

```

**Comment by Harmon758** [comment] 2019-07-31 06:49
`tweet_mode` can already be passed as a keyword-argument parameter for any API method that uses an endpoint that accepts that parameter, and the `full_text` field will be an attribute of the resulting Status object. There were only a few methods that required minor changes to handle the parameter.
Nothing needed to be added or changed for streams to support the addition of the `extended_tweet` field/attribute.

I've added [a section in the documentation that covers extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html) to supplement [Twitter’s Tweet updates documentation](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).
@kodeine @pau1a @Nebelhom 

@burndive 
> Tweepy needs to be updated to provide both a full_text and a text

The latter attribute is replaced by the former in a Tweet object when using extended mode, and this is reflected in the corresponding Status object.

> Tweepy should also natively surface the list of users that this tweet is a reply to.

I'm not sure how that relates to this issue, but there should ever only be one user a Tweet is a reply to, and all the `in_reply_to_` attributes of a Tweet object should be reflected in the corresponding Status object.

> Tweepy also needs support for the auto_populate_reply_metadata boolean parameter.

This was added with https://github.com/tweepy/tweepy/commit/17f73ed27472ee74ef4ec6e1722bc221482d7eff (#761) as part of Tweepy v3.6.0.

@Mandrewoid This is likely your encoding not supporting the ellipsis character, `…`, that Retweets are truncated with. This is normal behavior for Retweets.

@rosscg Are you sure that the Tweet in question is not a Retweet? If so, can you provide a reproducible example (MCVE/SSCCE)?

@Nebelhom 
This is normal behavior for Retweets.

You can also just use the `full_text` attribute of the (Retweeted) Status object from the `retweeted_status` attribute of the Status object (e.g. `tweet.retweeted_status.full_text`) to get the full text of the Retweeted Tweet, rather than going through the raw JSON.

> I did not find a good flag just yet to check if it is a retweet (only flags I found checked if this tweet was retweeted), so I used the 'RT' at the beginning as a handle. If someone finds a better one, I am glad to listen. It would make the code simpler.

From [Twitter's documentation for the Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object) itself:
> Retweets can be distinguished from typical Tweets by the existence of a `retweeted_status` attribute.

@burndive 
> My code above uses data found in the tweet._json structure.

This shouldn't be necessary, as the Status object should be fully representative of the corresponding JSON data used to generate it.

> ```
>         if 'retweeted_status' in tweet._json:
>             isRetweet = True
> 
> ```

For example, here, you can simply use the `retweeted_status` attribute of the Status object:
```py
        if hasattr(tweet, "retweeted_status"):
            isRetweet = True
```

**Closed by Harmon758** 2019-07-31 06:49 UTC
