### ISSUE TITLE
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

### ISSUE THREAD

**Issue by ScarletMcLearn** [tweepy/tweepy#908] opened 2017-07-14 17:36 UTC
I updated my streaming.py file like https://github.com/feinsteinben/tweepy/commit/a349d52545b9cbe07eb7471bae9b31436449b9f6?diff=split to fix the IncompleteRead exceptions but now this error is comming. Help!

I am getting this error:

Traceback (most recent call last):
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/http/client.py", line 583, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/http/client.py", line 630, in _safe_readinto
    raise IncompleteRead(bytes(mvb[0:total_bytes]), len(b))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 512 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/http/client.py", line 483, in readinto
    return self._readinto_chunked(b)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/http/client.py", line 594, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Tweepy Terminal.py", line 50, in <module>
    twitterStream.filter(track=["book"])
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/tweepy/streaming.py", line 458, in filter
    self._start(async)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/tweepy/streaming.py", line 372, in _start
    self._run()
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/tweepy/streaming.py", line 305, in _run
    six.reraise(*exc_info)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/tweepy/streaming.py", line 273, in _run
    self._read_loop(resp)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/tweepy/streaming.py", line 324, in _read_loop
    line = buf.read_line().strip()
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/tweepy/streaming.py", line 186, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/scarlet/anaconda3/envs/my_env/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by paulaldana23** [comment] 2018-03-01 22:14
Hello all,

I'm having similar issues as @ScarletMcLearn. Anyone has a possible work around yet?

Thanks,

Paul

**Comment by Lawrence-of-course** [comment] 2018-03-04 12:13
Hi All,

@paulaldana23 I am getting this error as well. Did you manage to find a solution or work around?

Thanks,
Law

**Comment by rokn1500** [comment] 2018-03-04 14:50
i have seen this too, no fix.

**Comment by paulaldana23** [comment] 2018-03-12 18:39
@Lawrence-of-course sadly, I haven't found any solution yet. =/

**Comment by diegoje** [comment] 2018-03-15 14:26
Same problem here - anybody has a fix to it?

**Comment by paulaldana23** [comment] 2018-03-16 20:48
Hello all,

I thought of a work around, although I'm not sure if it really works as the error only happens to me sporadically, making hard for me to debug the error. Not really much of a solution as I am just suppressing the errors, but it is better than having your program stop when the error occurs. 

I am just trying to catch the error then restart my stream. If anyone willing to try and post the result in this thread, that'll be great. Here's how I did mine..

Add these up top:
`from http.client import IncompleteRead as http_incompleteRead
from urllib3.exceptions import IncompleteRead as urllib3_incompleteRead`

then add these within your **on_data** function
`    def on_data(self, data):
        """
        This function overloads the on_data function in the tweepy package 
        It is called when raw data is received from tweepy connection.
        :param data: a dict of the tweets information
        :return: True/False. Return False to stop stream and close connection.
        """
        if (time.time() - self.startTime) < self.timeLimit:
            try:
                tweet = json.loads(data)
                # Filter out retweets
                if tweet['text'][:2] != 'RT':
                    self.printStreamingTweet(json.loads(data))
                    if not debug_mode:
                        self.tweetFound.emit(json.loads(data))
                    return [json.loads(data)]
            except BaseException as e:
                print("Error on_data: %s, Pausing..." % str(e))
                time.sleep(5)
                return True
            **except http_incompleteRead as e:
                print("http.client Incomplete Read error: %s" % str(e))
                print("~~~ Restarting stream search in 5 seconds... ~~~")
                time.sleep(5)
                #restart stream - simple as return true just like previous exception?
                return True
            except urllib3_incompleteRead as e:
                print("urllib3 Incomplete Read error: %s" % str(e))
                print("~~~ Restarting stream search in 5 seconds... ~~~")
                time.sleep(5)
                return True**
        else:
            if not debug_mode:
                self.tweetFound.emit(False)
            print('Timed out!')
            return False`

Again, not sure if this is going to work and certainly not the best solution. I'll really appreciate it if anyone would check and see if this would work for them.

Best of luck,

Paul

**Comment by rokn1500** [comment] 2018-03-16 22:49
thanks, looks interesting.
there seem to be a lot of issues like this.
discouraging

**Comment by diegoje** [comment] 2018-03-16 23:51
So here's how I fixed mine:

```python
auth = OAuthHandler(ckey, csecret)
auth.set_access_token(atoken, asecret)
twitterStream = Stream(auth, listener())

while True:
    try:
        twitterStream.filter(track=[chip], async=True)

    except (ProtocolError, AttributeError):
        continue
```

This way it ignores the error and carries on with the stream. Next step is to add a logging of some sort to keep track of when the issue is happening...

**Comment by peihainan** [comment] 2018-11-22 10:10
Possibly no enough disk.

**Comment by codeck313** [comment] 2019-03-13 05:08
This for me was happening due to lot of processing the the on_status function leading to a delay from the API output.The best way to do this was to use threading to not clog the function for too long

**Comment by Harmon758** [comment] 2019-04-26 22:43
Duplicate of #237 

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Closed by Harmon758** 2019-04-26 22:43 UTC

**Comment by s2t2** [comment] 2019-12-04 03:32
> This for me was happening due to lot of processing the the on_status function leading to a delay from the API output.The best way to do this was to use threading to not clog the function for too long

how does one do this?

**Comment by Harmon758** [comment] 2019-12-04 05:18
Please don't necrobump closed issues.
See https://docs.python.org/3/library/threading.html.
Also see #237 for further information on this issue.
