### ISSUE TITLE
Error: Media type unrecognized.

### ISSUE THREAD

**Issue by umar13893** [tweepy/tweepy#1304] opened 2019-12-12 12:16 UTC
I am getting this error "Media type unrecognized." after uploading these kinds of images. Uploading this image directly to twitter works fine but not through the API.

Image:
![d4f8dc5e-467c-4c75-8a98-03592bcf6e02](https://user-images.githubusercontent.com/13707584/70711132-91b63900-1d02-11ea-8b40-56b60d236415.jpg)

My Code:
```
images = []
for x in user_tweet_images_list: # AWS S3 image urls
    media_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=get_image_extension(x.tweet_image.url)
    )
    media_file.write(x.tweet_image.read())
    images.append(media_file.name)

media_ids = [api.media_upload(i).media_id_string for i in images]
post_tweet = api.update_status(status=user_tweet.tweet_message, media_ids=media_ids)
```

**Comment by Harmon758** [comment] 2019-12-12 12:58
This is likely a duplicate of #1060 and will probably be fixed when v3.9 is released with #1086.

**Comment by umar13893** [comment] 2019-12-12 17:34
Thanks, @Harmon758 get_image_extension already returning suffix with a dot(`.`)

**Comment by Harmon758** [comment] 2019-12-12 17:56
Ah, my mistake, I didn't realize that your error is actually a `TweepError` originating from Twitter's API. The likely issue is that you're uploading an empty file because you haven't flushed the data to the temporary file, e.g. with `media_file.flush()`.

**Closed** 2019-12-12 17:58 UTC
Labels: Invalid

**Comment by umar13893** [comment] 2019-12-12 18:23
Thanks @Harmon758 that working for me now.
