### ISSUE TITLE
missing "parameter" to List Tweets lookup

### ISSUE THREAD

**Issue by 11348** [tweepy/tweepy#1993] opened 2022-10-27 12:58 UTC
timeline = client.get_list_tweets(id=list_id,
                        expansions=["author_id", "attachments.poll_ids", "attachments.media_keys",
                                              "referenced_tweets.id", 'referenced_tweets.id.author_id',
                                              'in_reply_to_user_id'],
                                  media_fields=["url"],
                                  tweet_fields=['id', 'text', 'author_id', 'created_at', 'conversation_id', 'entities',
                                                'public_metrics', 'referenced_tweets'])

tweepy.errors.BadRequest: 400 Bad Request
The query parameter [media_fields] is not one of [id,max_results,pagination_token,expansions,tweet.fields,media.fields,poll.fields,place.fields,user.fields]

media.fields parameter should have in List Tweets lookup

https://developer.twitter.com/en/docs/twitter-api/lists/list-tweets/api-reference/get-lists-id-tweets

**Comment by Harmon758** [comment] 2022-10-27 14:43
This is a duplicate of #1931 and was fixed with https://github.com/tweepy/tweepy/commit/08d56844369f0b6868050ab53e86f953b450c2ff in [Tweepy v4.10.1](https://github.com/tweepy/tweepy/releases/tag/v4.10.1).

Please make sure you're using the latest version when submitting new issues.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Closed by Harmon758** 2022-10-27 14:43 UTC
