### ISSUE TITLE
Video support.

### ISSUE THREAD

**Issue by IoIxDButStronger** [tweepy/tweepy#1180] opened 2019-03-11 20:40 UTC
Issues about this were posted as early as [four years ago](https://github.com/tweepy/tweepy/pull/655). It's seems strange that the only way now to upload videos is with a fork of tweepy. Why hasn't it been implemented? There's still nothing in the docs about it, so if it IS implemented I apologize. But it seems weird that this branch specifically does not support video, yet forks of it do. I don't want to switch to a fork or leave this project, but I also want to be able to upload videos.

**Comment by fitnr** [comment] 2019-04-25 15:16
As the co-author of one of these forks, I agree. It appears that @Harmon758 has taken on a maintainer role, perhaps they can help with this.

**Comment by Harmon758** [comment] 2019-04-26 06:23
I have indeed taken up the task of cleaning up and organizing the issues and PRs.
I'm still in the process of doing that though, so give me some time before I handle this one.
I know it's one of the more requested features, but it's also one of the more complex.

**Comment by Harmon758** [comment] 2019-05-06 00:16
Going to close this as duplicate of #640 for now.

**Closed by Harmon758** 2019-05-06 00:16 UTC
Labels: Feature, Task
