### ISSUE TITLE
Cannot set filter to stream

### ISSUE THREAD

**Issue by cgore1** [tweepy/tweepy#656] opened 2015-09-30 06:22 UTC
I am using stream API to get streams from tweepy.

When I do simple call,

stream = tweepy.Stream(auth, l)
stream.filter(track=['programming'])

I am getting following error. - 

Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "C:\Python34\lib\site-packages\tweepy-3.4.0-py3.4.egg\tweepy\streaming.py", line 286, in _run
    raise exception
  File "C:\Python34\lib\site-packages\tweepy-3.4.0-py3.4.egg\tweepy\streaming.py", line 255, in _run
    self._read_loop(resp)
  File "C:\Python34\lib\site-packages\tweepy-3.4.0-py3.4.egg\tweepy\streaming.py", line 298, in _read_loop
    line = buf.read_line().strip()
  File "C:\Python34\lib\site-packages\tweepy-3.4.0-py3.4.egg\tweepy\streaming.py", line 171, in read_line
    self._buffer += self._stream.read(self._chunk_size)
TypeError: Can't convert 'bytes' object to str implicitly

It has been hours since I tried every combination and nothing works. Please help me out here!

**Comment by koitaroh** [comment] 2015-10-15 10:58
Refer #615

**Comment by Harmon758** [comment] 2019-04-25 08:36
Duplicate of #615

**Closed by Harmon758** 2019-04-25 08:36 UTC
