### ISSUE TITLE
Tweepy Streaming not working in Python 3.7

### ISSUE THREAD

**Issue by pragyaalagh** [tweepy/tweepy#1097] opened 2018-09-04 07:00 UTC
I used the following code to stream data via Tweepy in Python 3.7
However, it always returns an error like this:
I am assuming that it is not taking the **async attribute** anymore in Python 3.7. 
**When I ran streaming.py from my system in the local tweepy module folder, it still showed an error for the async attribute as invalid syntax.**

Error:-
```
File "C:\Users\Student\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax
```

Code:-
```
auth=tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_key, access_secret)
api=tweepy.API(auth)

class MyStreamListener(tweepy.StreamListener):

    def on_data(self, data):
        print(data)
        return True
    
    def on_error(self, status):
        print(status)
        
myStreamListener = MyStreamListener()
myStream = Stream(api.auth, listener=myStreamListener)
myStream.filter(track=['hello'])

```

**Comment by Harmon758** [comment] 2018-09-04 07:04
Duplicate of #1017 and fixed with #1042.
When submitting issues, please make sure you're on the most recent development version.
Otherwise, see #1063.

**Closed** 2018-09-09 09:51 UTC

**Comment by abahjoel** [comment] 2019-01-11 11:36
ok,thanks.I installed tweepy through pip on command line.
i.e pip install python -m tweepy textblob matplotlib
All at the same time.

**Comment by fajarmf10** [comment] 2019-04-21 03:38
The documentation seems out-of-date. It should be **is_async** on [Streaming docs](http://docs.tweepy.org/en/stable/streaming_how_to.html)

**Comment by Harmon758** [comment] 2019-04-21 05:27
@fajarmf10 See #1184

**Comment by abahjoel** [comment] 2019-07-09 10:55
I tried it and it is working now.My challenge now is how to stream tweets
into a database,say mysql,do sentiment analysis and have results displayed
in a chart, say piechart.Is there any help on this?

**Comment by Harmon758** [comment] 2019-07-31 05:08
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python or other software.
