### ISSUE TITLE
Tweepy stream incomplete read error super high amounts of tweets

### ISSUE THREAD

**Issue by Hunterhusker** [tweepy/tweepy#1163] opened 2019-01-23 18:07 UTC
So straight off the bat I would like to reference this problem here https://github.com/tweepy/tweepy/issues/448 I think it is most certainly having a similar issue, but as it is from almost 5 years ago, I thought I would open a new thread to see if anything has changed since 2014 to help me. I am receiving probably the highest amount of tweets that anyone has used this bot for. I am using this bot to track when Donald Trump tweets, and then play America the Beautiful and flash an LED to the song. Lets not get into politics, but if you haven't noticed people like to constantly tweet at him, and so by having my bot follow him I am getting a super huge influx of tweets 24/7, non stop. I have a video somewhere where I printed out the names of the tweeters holy moly, at least 3 a second. Anyway I just want to say this bot is crashing periodically with super large amounts of tweets coming through. It probably wasn't designed for this. Is there anyway to make it only follow tweets made by the user and not tweets at the user, because that would fix a lot of my problems. The specific error is an incomplete read error, I assume from tweets coming and going so fast it cannot be processed.  I am filtering them out with a tag and user check function to see what tweets actually make it to my main loop, but I think maybe there is more I can do to keep it running longer.

**Comment by Harmon758** [comment] 2019-04-27 00:50
> Is there anyway to make it only follow tweets made by the user and not tweets at the user

In short, no. The only parameter the Twitter API's [statuses/filter endpoint](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) has for following a specific user is `follow`, which:

> For each user specified, the stream will contain:
> 
> - Tweets created by the user.
> - Tweets which are retweeted by the user.
> - Replies to any Tweet created by the user.
> - Retweets of any Tweet created by the user.
> - Manual replies, created without pressing a reply button (e.g. `@twitterapi I agree`).

See https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters.

You'll have to filter out other Tweets yourself.
Otherwise this issue is a duplicate of #237 (and #448).

**Closed by Harmon758** 2019-04-27 00:50 UTC
