### ISSUE TITLE
InstallError: TypeError: parse_requirements() got an unexpected keyword argument 'session'

### ISSUE THREAD

**Issue by suresh-ejs** [tweepy/tweepy#995] opened 2018-01-29 13:01 UTC
Am installing tweepy 3.5 on my win 10 and Initially i got error that no pip found, so i created a blank folder and file. Now am getting the error "TypeError: parse_requirements() got an unexpected keyword argument 'session'"

**Comment by Harmon758** [comment] 2019-01-22 19:08
Duplicate of #564

**Closed** 2019-04-24 17:34 UTC
Labels: Duplicate
