### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by catleeball** [tweepy/tweepy#1298] opened 2019-11-24 01:50 UTC
Twitter supports WebP images, and it would be nice for Tweepy to also allow them.

After chatting with @Harmon758  on discord, he said he was replacing mimetypes with imghd. WebP would be good to add support for after the imghd refactor.

Thanks team! 😃

**Comment by Harmon758** [comment] 2019-11-24 07:01
To clarify, #1086 will likely be merged once I review it and if there aren't any issues with it.
Otherwise, imghdr will likely be added as a fallback method.

**Comment by shuuji3** [comment] 2020-01-11 08:22
Hi, according to [the official documentation](https://docs.python.org/3.5/library/imghdr.html), the feature to detect `webp` was added to `imghdr` since Python v3.5.

I confirmed that a webp image can be handled with the `imghdr.what()` method as I expected as shown in #1086. Below is the results on the Python3 Docker container.

```shell
> docker run --name python -it -v $(pwd):/dwn python:3.8.1-alpine sh

/dwn # ls -la img.webp
-rw-------    1 root     root         22458 Jan 11 07:57 img.webp

/dwn # ipython
Python 3.8.1 (default, Jan  3 2020, 23:04:34)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import imghdr

In [2]: imghdr.what('img.webp')
Out[2]: 'webp'
```

**Closed** 2020-02-13 21:35 UTC
Labels: Improvement
