### ISSUE TITLE
tweet_mode='extended' is undocumented on API.user_timeline but works

### ISSUE THREAD

**Issue by tgriffinrevel** [tweepy/tweepy#1170] opened 2019-02-05 17:12 UTC
[API.user_timeline](https://tweepy.readthedocs.io/en/v3.5.0/api.html#API.user_timeline) does not state that `tweet_mode` is a valid parameter, but when I used it (`tweet_mode=extended`), it returned the tweets with the `full_text` attribute.

It works perfectly, it's just undocumented.

**Comment by ca1ek** [comment] 2019-02-25 12:54
nothing is documented in this library

i still haven't been able to find the doc for the Status object

**Comment by sysgenerated** [comment] 2019-03-10 01:23
I'm still getting truncated text with both user_timeline and get_status:

print(api.get_status(id=1103767535982469121, tweet_mode='extended').full_text)

This prints:
"RT @FLOTUS: Honored to celebrate a group of extraordinary women today at the @StateDept’s #WomenofCourage ceremony.  These women are making…"

From this source:
"RT @FLOTUS: Honored to celebrate a group of extraordinary women today at the @StateDept’s #WomenofCourage ceremony. These women are making a real impact around the globe!"

**Comment by booxter** [comment] 2019-05-24 07:22
@sysgenerated not sure but it clearly works in my fork of `turses` that passes `tweet_mode="extended"` into timeline / favorites endpoints.

**Comment by ZheyuYe** [comment] 2019-06-17 13:49
Thanks, that solved my issue of truncated text fields with `tweet_mode='extended'`

**Comment by Harmon758** [comment] 2019-07-31 06:08
I've added [a section in the documentation that covers extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html) to supplement [Twitter’s Tweet updates documentation](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).

I'm going to close this, as that reflects Twitter's documentation, which also does not list it as a parameter for every method that accepts it.

@sysgenerated That is normal behavior for Retweets. To get the full text of the Retweeted Tweet, you can use the `full_text` attribute of the Status object from the `retweeted_status` attribute.

**Closed by Harmon758** 2019-07-31 06:08 UTC

**Comment by mansi-aggarwal-2504** [comment] 2020-02-27 11:00
Hello, I am using tweet_mode=extended param (premium API). But I am getting the following message:
{
    "error": {
        "message": "There were errors processing your request: Unknown parameter:'tweet_mode'",
        "sent": "2020-02-27T10:51:58+00:00",
        "transactionId": "0060fa8d00049997"
    }
}

My request URL is: https://api.twitter.com/1.1/tweets/search/fullarchive/label.json?query=some keywords -filter:retweets&fromDate=201908080000&toDate=201908082359&tweet_mode=extended

What might be the problem?

**Comment by DGaffney** [comment] 2021-06-28 21:40
This does not appear to work as of June 2021 - running it on `user_timeline` returns truncated texts every time. Should it not? Currently on version 3.10.0.

**Comment by Harmon758** [comment] 2022-02-14 02:09
Please don't necrobump old closed issues.
I'm unable to reproduce this, but feel free to open a new issue if you have a reproducible example (MCVE/SSCCE) with the latest version of Tweepy.
