### ISSUE TITLE
statuses_lookup: AttributeError: 'unicode' object has no attribute 'items

### ISSUE THREAD

**Issue by sam-s** [tweepy/tweepy#984] opened 2018-01-02 02:17 UTC
I get this backtrace:
```
      1 
      2 completely_missing = api.statuses_lookup(list(remaining_ghosts),map_=True,
----> 3                                          include_entities=True)
      4 len(completely_missing)

/home/sds/.virtualenvs/algorisk/local/lib/python2.7/site-packages/tweepy/api.pyc in statuses_lookup(self, id_, include_entities, trim_user, map_)
     97                         trim_user=None, map_=None):
     98         return self._statuses_lookup(list_to_csv(id_), include_entities,
---> 99                                      trim_user, map_)
    100 
    101     @property

/home/sds/.virtualenvs/algorisk/local/lib/python2.7/site-packages/tweepy/binder.pyc in _call(*args, **kwargs)
    245             return method
    246         else:
--> 247             return method.execute()
    248 
    249     # Set pagination mode

/home/sds/.virtualenvs/algorisk/local/lib/python2.7/site-packages/tweepy/binder.pyc in execute(self)
    230 
    231             # Parse the response payload
--> 232             result = self.parser.parse(self, resp.text)
    233 
    234             # Store result into cache if one is available.

/home/sds/.virtualenvs/algorisk/local/lib/python2.7/site-packages/tweepy/parsers.pyc in parse(self, method, payload)
    100 
    101         if method.payload_list:
--> 102             result = model.parse_list(method.api, json)
    103         else:
    104             result = model.parse(method.api, json)

/home/sds/.virtualenvs/algorisk/local/lib/python2.7/site-packages/tweepy/models.pyc in parse_list(cls, api, json_list)
     63         for obj in json_list:
     64             if obj:
---> 65                 results.append(cls.parse(api, obj))
     66         return results
     67 

/home/sds/.virtualenvs/algorisk/local/lib/python2.7/site-packages/tweepy/models.pyc in parse(cls, api, json)
     77         status = cls(api)
     78         setattr(status, '_json', json)
---> 79         for k, v in json.items():
     80             if k == 'user':
     81                 user_model = getattr(api.parser.model_factory, 'user') if api else User

AttributeError: 'unicode' object has no attribute 'items'
```
Note that the error only happens with `map_=True`, without it there is no error.

**Comment by ZeerakW** [comment] 2018-01-10 11:42
You need to convert it to a dict as the JSON element _should_ just be a string.

**Comment by sam-s** [comment] 2018-01-10 14:14
who is "you"? the user? the developer?
what is "it"? an argument to `api.statuses_lookup`? some internal variable?

**Comment by ZeerakW** [comment] 2018-01-10 14:18
Sorry was a bit quick. The element you get back from _json is a JSON object, that is a string - a unicode string as it would be (hence the reference to unicode object in the error message). If you, the developer, convert your JSON object to a dict, it will then have the items() method you're trying to use.

**Comment by sam-s** [comment] 2018-01-10 14:42
I am a user of the package, not the package developer.
I called a documented function.
I got an error.

Are you suggesting a fix to the package or a workaround for my code?

**Comment by ZeerakW** [comment] 2018-01-10 14:45
Oh right, sorry. I missed that it was it was in the Tweepy code. It looked like it was in your own code. Do you know if this error also happens in python 3?

**Comment by sam-s** [comment] 2018-01-10 22:34
With this patch:
```
--- a/tweepy/models.py
+++ b/tweepy/models.py
@@ -76,6 +76,8 @@ class Status(Model):
     def parse(cls, api, json):
         status = cls(api)
         setattr(status, '_json', json)
+        if not hasattr(json, "items"):
+            return status
         for k, v in json.items():
             if k == 'user':
                 user_model = getattr(api.parser.model_factory, 'user') if api else User
```
the error disappears, but the return value is
```
[Status(_api=<tweepy.api.API object at 0x7ff96008e510>, _json=u'id')]
```
IOW, the offending string is `id` -- not very useful anyway.

**Comment by Harmon758** [comment] 2019-05-03 22:34
Duplicate of #598 

As that issue outlines, the format of the response from the API changes with map/`map_` set to `True`.
Since it's now a dictionary instead of a list, `Model.parse_list` attempts to iterate over the singular `"id"` key of the dictionary, resulting in the behavior you see with your patch.

**Closed by Harmon758** 2019-05-03 22:34 UTC
