### ISSUE TITLE
Update docs regarding trends() mehtods

### ISSUE THREAD

**Issue by chimeno** [tweepy/tweepy#465] opened 2014-08-01 00:51 UTC
The actual [api doc](http://tweepy.readthedocs.org/en/v2.3.0/api.html#API.trends) says there are `trends`, `trends_current`, `trends_daily` and `trends_weekly`, but in 2.3.0 the actual methods are: `api.trends_available` , `api.trends_closest`    `api.trends_daily` ,     `api.trends_place` and    ``api.trends_weekly`

**Comment by rajasimon** [comment] 2018-04-24 10:12
Also doc says `Returns the top 10 trending topics` but returns lot of them. Why ?

**Comment by niranjantdesai** [comment] 2019-04-19 22:48
> Also doc says `Returns the top 10 trending topics` but returns lot of them. Why ?

With WOEID 1, the top 10 trending topics were returned. But when I tried with the WOEID for USA, I got the top 50 trends.

**Comment by Harmon758** [comment] 2019-05-03 21:26
This has been resolved with https://github.com/tweepy/tweepy/commit/cbcb62f251ff64626d940cb3d29fc5ea76494f5a and https://github.com/tweepy/tweepy/commit/3c0d993ff8d76debd15460ba7647297a559da142 in Tweepy v3.2.0.

@rajasimon The documentation was outdated and has been updated with https://github.com/tweepy/tweepy/commit/de51cf03397c94c65c5436dc0951cda7214ff5a0 to reflect the documentation at https://developer.twitter.com/en/docs/trends/trends-for-location/api-reference/get-trends-place.

@niranjantdesai I'm unable to reproduce this. I'm getting 50 trends for WOEID 1, e.g.:
```py
>>> len(api.trends_place(1)[0]["trends"])
50
```
Regardless, the documentation *does* say "if trending information is available for it".

**Closed by Harmon758** 2019-05-03 21:26 UTC
