### ISSUE TITLE
upload 10MB gif

### ISSUE THREAD

**Issue by reisenmachtfreude** [tweepy/tweepy#1359] opened 2020-05-06 21:17 UTC
uploading a large gif (10MB) results in an error:
    raise TweepError('File is too big, must be less than %skb.' % max_size)
tweepy.error.TweepError: File is too big, must be less than 4883kb.

On twitter API they state gif has limit of 15MB

Can somebody help?

**Comment by MichaelCurrin** [comment] 2020-05-07 10:04
Check the existing issues - there's already one and it has an unmerged PR.

https://github.com/tweepy/tweepy/issues/1336

---

Some references would help in future, but I found what you meant and it looks like a bug.

> Image size <= 5 MB, animated GIF size <= 15 MB

https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices

And in Tweepy, there is a limit https://github.com/tweepy/tweepy/blob/v3.8.0/tweepy/api.py#L200

`4883`

And that gets multiplied by `1024` here to get to just over 5 MB.

https://github.com/tweepy/tweepy/blob/v3.8.0/tweepy/api.py#L1297

**Comment by MichaelCurrin** [comment] 2020-05-07 10:07
---

Some references would help in future, but I found what you meant and it looks like a bug.

> Image size <= 5 MB, animated GIF size <= 15 MB

https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices

And in Tweepy, there is a limit https://github.com/tweepy/tweepy/blob/v3.8.0/tweepy/api.py#L200

`4883`

And that gets multiplied by `1024` here to get to just over 5 MB.

https://github.com/tweepy/tweepy/blob/v3.8.0/tweepy/api.py#L1297

**Comment by reisenmachtfreude** [comment] 2020-05-08 20:46
Thank you for your reply. Correct, I meant the link you wrote.
I was unable to find any pyhton twitter library which is able to upload 10MB gif files.

However, the following nodejs implementation does the job correctly
https://github.com/ttezel/twit see postMediaChunked method

**Comment by MichaelCurrin** [comment] 2020-05-09 07:21
Use that if you need to. Until the the PR work above is merged and you don't want to mess with branches to reinstall from, then you can always modify your installed tweepy locally (without using git, github etc.) and replace the 4883 number with a much higher number. The filename in the PR will show you where to change

**Comment by Harmon758** [comment] 2020-07-01 22:24
Duplicate of #1336

**Closed by Harmon758** 2020-07-01 22:24 UTC
