### ISSUE TITLE
Fixing quick replies & ctas in send_direct_message function

### ISSUE THREAD

**Issue by research555** [tweepy/tweepy#1483] opened 2020-12-26 18:08 UTC
quick reply options needs to be added to the function, along with some minor modifications to the quick_reply_type condition. I have done this myself but figured I'd let you know. Also, currently there's no way of creating call to action buttons. I have tried to do this myself but I keep getting `tweepy.error.TweepError: [{'code': 214, 'message': "event.message_create.message_data.ctas: '' is not a valid Seq"}]
`
Some help would be nice

**Comment by Harmon758** [comment] 2020-12-26 23:53
Partially duplicate of #1280

**Closed** 2020-12-26 23:56 UTC
Labels: Duplicate, Feature, Improvement
