### ISSUE TITLE
How do I get tweets with an embedded URL?

### ISSUE THREAD

**Issue by AkshayChan** [tweepy/tweepy#1118] opened 2018-10-22 07:10 UTC
How can i extract tweets with Tweepy that contain an embedded URL, for example a youtube link to a video? I have been going through the Twitter API documentation but I am still pretty confused.

Thanks

**Comment by Harmon758** [comment] 2018-12-10 17:58
Duplicate of #1120

**Closed** 2019-04-24 16:55 UTC
Labels: Duplicate
