### ISSUE TITLE
How to retrieving media and download?

### ISSUE THREAD

**Issue by ly1n** [tweepy/tweepy#1401] opened 2020-07-06 07:05 UTC
Hi!

I got DM through `API.get_direct_message()`. And I get the `media_url` or `expanded_url` or `display_url`.
But this URL can't access.

I want to read or download DM media, what should I do?

I found this document `https://developer.twitter.com/en/docs/direct-messages/message-attachments/guides/retrieving-media`, but I don't know how to use with tweepy.
I've been looking for hours, But it hasn't been solved.

The DM object like this:
```
message_create={
    'target': {
        'recipient_id': 'xxx'
    },
    'sender_id': 'xxx',
    'source_app_id': 'xxx',
    'message_data': {
        'text': 'https://t.co/xxx',
        'entities': {
            'hashtags': [],
            'symbols': [],
            'user_mentions': [],
            'urls': [{
                'url': 'https://t.co/xxx',
                'expanded_url': 'https://twitter.com/messages/media/xxx',
                'display_url': 'pic.twitter.com/xxx',
                'indices': [6, 29]
            }]
        },
        'attachment': {
            'type': 'media',
            'media': {
                'id': xxx,
                'id_str': 'xxx',
                'indices': [6, 29],
                'media_url': 'https://ton.twitter.com/1.1/ton/data/dm/xxx/xxx.jpg',
                'media_url_https': 'https://ton.twitter.com/1.1/ton/data/dm/xxx/xxx.jpg',
                'url': 'https://t.co/xxx',
                'display_url': 'pic.twitter.com/xxx',
                'expanded_url': 'https://twitter.com/messages/media/xxx',
                'type': 'photo',
                'sizes': {
                    'thumb': {
                        'w': 150,
                        'h': 150,
                        'resize': 'crop'
                    },
                    'large': {
                        'w': 1500,
                        'h': 500,
                        'resize': 'fit'
                    },
                    'medium': {
                        'w': 1200,
                        'h': 400,
                        'resize': 'fit'
                    },
                    'small': {
                        'w': 700,
                        'h': 300,
                        'resize': 'fit'
                    }
                }
            }
        }
    }
}
```

**Comment by OnlyOneMoreHour** [comment] 2020-10-31 04:37
Did you try to get the file directly with request?

**Comment by ly1n** [comment] 2020-10-31 06:02
> 
> 
> Did you try to get the file directly with request?

The file request needs account permission, so it can't be requested directly. The request needs authentication.

**Comment by OnlyOneMoreHour** [comment] 2020-11-06 12:29
Post the error plz

**Comment by Harmon758** [comment] 2020-12-30 00:31
Duplicate of #1314

**Closed by Harmon758** 2020-12-30 00:31 UTC
