### ISSUE TITLE
Installation from github failed

### ISSUE THREAD

**Issue by hj91** [tweepy/tweepy#607] opened 2015-05-11 03:36 UTC
sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
TypeError: parse_requirements() got an unexpected keyword argument 'session'

do i need to login as root?

**Comment by 7diracseas** [comment] 2015-05-11 10:09
Looks like someone messed up [here](https://github.com/tweepy/tweepy/commit/9b4cb9eb123be05a925c1c6deaf0141699853644#diff-2eeaed663bd0d25b7e608891384b7298).

**Comment by Harmon758** [comment] 2019-01-22 19:07
Duplicate of #564

**Closed** 2019-04-24 18:30 UTC
Labels: Duplicate
