### ISSUE TITLE
Twitter V2

### ISSUE THREAD

**Issue by Ces-D** [tweepy/tweepy#1423] opened 2020-09-02 04:35 UTC
There wouldn't happen to be any support for Twitter developer api v2. It is still in testing, but if your trying to get metrics it is very useful.

**Comment by NicholasMamo** [comment] 2020-11-01 11:24
Bumping this to ask: since v2 is out in early-access and seems stable, does tweepy have plans to support the new version in the near future?

**Comment by lucasrangit** [comment] 2020-11-02 20:22
Duplicate of #1396

**Comment by Harmon758** [comment] 2020-12-18 06:16
I'm going to close this in favor of #1472. Apologies for the delay in responding.

**Closed by Harmon758** 2020-12-18 06:16 UTC
