### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Juanca18** [tweepy/tweepy#978] opened 2017-12-20 20:23 UTC
I have this error when executing luckyBot.py

Traceback (most recent call last):
  File "D:\BOT\LuckyBot-master\LuckyBot-master\src\luckyBot.py", line 30, in <module>
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
AttributeError: module 'tweepy' has no attribute 'OAuthHandler'

Tengo las key(token,api) bien

**Comment by animenon** [comment] 2017-12-23 18:49
Check: https://stackoverflow.com/questions/41917038/module-tweepy-has-no-attribute-oauthhandler#41924762

**Comment by anveshd1** [comment] 2018-02-07 23:01
I have this error

No module named 'tweepy.auth'

**Comment by Harmon758** [comment] 2019-04-24 19:39
This should be fixed with https://github.com/tweepy/tweepy/commit/d9d5a8648d738c660fc0a457523d0083d03c2353 since v3.0.0, and I'm unable to reproduce this with 3.7.0.
Make sure you don't have another file or module named "tweepy" in the project or in your path.

**Closed by Harmon758** 2019-04-24 19:39 UTC
