### ISSUE TITLE
How can i post video with tweepy?

### ISSUE THREAD

**Issue by maksymkv25** [tweepy/tweepy#800] opened 2016-10-17 10:22 UTC
Hello, i don't find video post in tweepy doc's, is it possible?
And if so, how can i upload video?

**Comment by fitnr** [comment] 2016-10-17 14:01
There's an open pull request (#672) languishing on this, but it's not currently part of the library. You can use the alternate version, though.

**Comment by maximkv25** [comment] 2016-10-17 17:46
I try it. And have some problem with posting video
`video = 'E:\\example.mp4'
media = api.upload_chunked(video)`
got it 
`Media(media_id=788066364296691712, expires_after_secs=86400, media_id_string='788066364296691712', video={'video_type': 'video/mp4'}, _api=<tweepy.api.API object at 0x0000000004421C18>, size=1291103)`
and how to post? can explain please?

**Comment by fitnr** [comment] 2016-10-18 02:30
I guess the Tweepy docs are a little vague on updating with media. The [Twitter docs](https://dev.twitter.com/rest/reference/post/statuses/update) provide some hints.

It would go like this:
```python
media = api.upload_chunked(video)
api.update_status(status="Hello World!", media_ids=[media.media_id])
```

The `media_ids` param expects a list because one can upload up to four pictures.

**Comment by maximkv25** [comment] 2016-10-18 07:06
Thank's)

2016-10-18 5:30 GMT+03:00 Neil Freeman <notifications@github.com>:

**Comment by staringispolite** [comment] 2017-10-13 02:11
@fitnr What version is that in? I'm on 3.5.0 and I get `AttributeError: 'API' object has no attribute 'upload_chunked'`

**Comment by fitnr** [comment] 2017-10-13 02:17
It's not in any version, it's an open pull request. The one mentioned above has been superseded by #929.

**Comment by staringispolite** [comment] 2017-10-14 07:30
Poking back in to confirm that using the branch the PR came from in #929, I was able to get video upload working. Just found the directory pip installed tweepy in, and overwrote it with the /tweepy folder from the video_upload2 branch of https://github.com/conversocial/tweepy/

Note that there's a bug in Twitter's API where a video needs to finish processing before you can successfully tweet with it. Best workaround I found was time.sleep() between the upload and status update calls https://twittercommunity.com/t/why-not-valid-video/72486/3

**Comment by Harmon758** [comment] 2019-05-06 00:14
Closing as duplicate of #640. See also #1180.

**Closed by Harmon758** 2019-05-06 00:14 UTC
