### ISSUE TITLE
Access Token must be provided for OAuth1.0a User Context

### ISSUE THREAD

**Issue by ZachHandley** [tweepy/tweepy#2150] opened 2023-08-03 03:38 UTC
### Summary

This damn thing don't work

### Reproduction Steps

OKAY. I AM QUITE FRUSTRATED SO I SHALL START AT THE BEGINNING.

It all began about 5 hours ago when I saw that Tweepy looked like it could help me out. Then I tried reading the docs. I did the three legged auth until I was, well using it, and it refused to get me `get_home_timeline` due to an unauthorized error.

OKAY, so I went to Client now with OAuth2 flow, and yet STILL I get an error about `Access Token must be provided for OAuth 1.0a User Context` even when running this shit with Client and OAuth2 and trying every different value for `Client` under the sun. And I'm sorry I'm annoyed and swearing, I really shouldn't be, but holy crap this is so frustrating for something that shouldn't be this difficult.

Why in the world does Client use OAuth1? I even tried the OAuth2 endpoints *specifically* and still get the same damn error.

### Minimal Reproducible Example

```python
@app.route("/login/<user_id>")
def login(user_id: str):
    if session.get("CONSUMER_KEY") is None or session.get("CONSUMER_SECRET") is None:
        session["CONSUMER_KEY"] = CONSUMER_KEY
        session["CONSUMER_SECRET"] = CONSUMER_SECRET

    print(f"Login with user_id {user_id}")
    session["user_id"] = user_id

    try:
        # redirect user to authorize app
        redirect_url = auth.get_authorization_url()
        session["authorization_url"] = redirect_url
        print(f"Redirecting to {redirect_url}")
        return redirect(redirect_url)

    except tweepy.TweepError:
        print("Error! Failed to get request token")


@app.route("/callback")
async def callback():
    print(f"In callback OAuth2: {request.args}")
    # verifier = request.args["oauth_verifier"]
    # oauth_token = request.args["oauth_token"]
    # get access token
    access_token = auth.fetch_token(request.url)

    print(f"Access token: {access_token}")
    session["access_token"] = access_token
    refresh_token = access_token["refresh_token"]

    # # store access token
    print("Set tokens for user")

    if session["user_id"] is None:
        print("No user_id found in session")
        return "Error: No user ID found in session."

    # # store in database
    save_to_db(session["user_id"], access_token, refresh_token)
    get_tweets(
        tweepy.Client(
            bearer_token=access_token["access_token"],
        )
    )

    return "Success! Logged in."


@app.route("/get_user_tweets/<user_id>")
def get_user_tweets(user_id: str):
    if not db_manager.check_twitter_user(user_id):
        return "Error: User has not authenticated with Twitter."
    # get user's access token and access token secret from database
    user = db_manager.get_twitter_user(user_id)
    access_token = user["twitter_access_token"]
    expires_at = user["expires_at"]
    expiry_date = datetime.fromisoformat(expires_at)
    now = datetime.now().replace(tzinfo=expiry_date.tzinfo)
    print(f"Access token expires at: {expiry_date}\nIt is currently {now}")
    if now > expiry_date:
        access_token = auth.refresh_token(refresh_token=user["twitter_refresh_token"])
        save_to_db(user_id, access_token, user["twitter_refresh_token"])
    client = tweepy.Client(
        bearer_token=access_token["access_token"],
    )
    me = client.get_me(user_auth=False)
    print(f"Me is {me}")

    # get tweets
    return get_tweets(client)


def get_tweets(client: tweepy.Client):
    public_tweets = client.get_home_timeline(max_results=1)
    print(public_tweets)
    print(f"Just in case that last one sucked\n{json.dumps(public_tweets)}")
    return public_tweets
```

### Expected Results

I get the g damn tweets

### Actual Results

401 Unauthorized, 403 Forbidden (when I tried to include access token and the other thing), and an `Access token must be provided blah blah blah` errors

### Twitter API Access Plan

Free

### Tweepy Version

4.14.0

### Checklist

- [X] I have searched for duplicate issues.
- [ ] If applicable, I have shown the entire traceback.
- [ ] If applicable, I have removed any visible credentials from my code and/or screenshots.

### Additional Context

I don't have a ton of additional context. The login flow works successfully, the error is on either Twitter or Tweepy's side or the documentation is not written well enough. Because the Client OAuth should _use_ the Client Oauth but whatever just can anyone help me understand this.

**Comment by Harmon758** [comment] 2023-08-03 03:44
`Client` supports both OAuth 1.0a and OAuth 2.0 because Twitter API v2 does.

What's the full traceback?

**Comment by ZachHandley** [comment] 2023-08-03 03:46
```
Traceback (most recent call last):
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/zachhandley/Documents/GitHub/TwitterPy/server.py", line 85, in callback
    me = client.get_me()
         ^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweepy/client.py", line 2535, in get_me
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweepy/client.py", line 69, in request
    auth = OAuth1UserHandler(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweepy/auth.py", line 31, in __init__
    raise TypeError("Consumer key must be string or bytes, not "
TypeError: Consumer key must be string or bytes, not NoneType
```

and this is after doing *everything* it says in the OAuth2.0PKCE flow

**Comment by ZachHandley** [comment] 2023-08-03 03:48
This is the other error I get
```
Traceback (most recent call last):
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/zachhandley/Documents/GitHub/TwitterPy/server.py", line 85, in callback
    me = client.get_me(user_auth=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweepy/client.py", line 2535, in get_me
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweepy/client.py", line 100, in request
    raise Forbidden(response)
tweepy.errors.Forbidden: 403 Forbidden
Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].
```

**Comment by Harmon758** [comment] 2023-08-03 03:58
The code in the first traceback, `me = client.get_me()` is different than in your example.
[`Client.get_me`](https://tweepy.readthedocs.io/en/v4.14.0/client.html#tweepy.Client.get_me) uses OAuth 1.0a by default. You need to specify `user_auth` as `False` like in your example code. This is documented.

The second traceback seems to indicate you're passing an app-only bearer token or at least, an invalid access token. Your code above is not minimally reproducible, and I'm not sure what `user["twitter_access_token"]` is. You'll need to provide all the relevant code or a reproducible example for further help.

**Comment by ZachHandley** [comment] 2023-08-03 04:09
Okay fine. Here's literally everything in my file. I'm not exaggerating I've literally tried everything I can think of. I used `get_me` without `user_auth` and with consumer secret and everything. I'm not posting here because I tried 2 things and gave up. I went through the entire adding OAuth1.0a process, until that bugged, and I figured I needed 2.0, and then now this is happening.
```
SCOPES = [
    "tweet.read",
    "tweet.write",
    "users.read",
    "follows.read",
    "offline.access",
    "like.read",
]

# Configure Redis for storing the session data on the server-side
app.config["SESSION_TYPE"] = "redis"
app.config["SESSION_PERMANENT"] = False
app.config["SESSION_USE_SIGNER"] = True
app.config["SESSION_REDIS"] = redis.from_url("redis://localhost:6379")

server_session = Session(app)

auth = tweepy.OAuth2UserHandler(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    redirect_uri="https://localhost:5172/callback",
    scope=SCOPES,
)
client: tweepy.Client


@app.route("/login/<user_id>")
def login(user_id: str):
    if session.get("CONSUMER_KEY") is None or session.get("CONSUMER_SECRET") is None:
        session["CONSUMER_KEY"] = CONSUMER_KEY
        session["CONSUMER_SECRET"] = CONSUMER_SECRET

    print(f"Login with user_id {user_id}")
    session["user_id"] = user_id

    try:
        # redirect user to authorize app
        redirect_url = auth.get_authorization_url()
        session["authorization_url"] = redirect_url
        print(f"Redirecting to {redirect_url}")
        return redirect(redirect_url)

    except tweepy.TweepError:
        print("Error! Failed to get request token")


@app.route("/callback")
async def callback():
    print(f"In callback OAuth2: {request.args}")
    # verifier = request.args["oauth_verifier"]
    # oauth_token = request.args["oauth_token"]
    # get access token
    access_token = auth.fetch_token(request.url)

    print(f"Access token: {access_token}")
    session["access_token"] = access_token
    refresh_token = access_token["refresh_token"]

    # # store access token
    print("Set tokens for user")

    if session["user_id"] is None:
        print("No user_id found in session")
        return "Error: No user ID found in session."

    # # store in database
    client = tweepy.Client(access_token)
    me = client.get_me(user_auth=False)
    print(f"Me is {me}")
    save_to_db(session["user_id"], access_token, refresh_token)
    get_tweets(
        tweepy.Client(
            access_token["access_token"],
        )
    )

    return "Success! Logged in."


@app.route("/get_user_tweets/<user_id>")
def get_user_tweets(user_id: str):
    if not db_manager.check_twitter_user(user_id):
        return "Error: User has not authenticated with Twitter."
    # get user's access token and access token secret from database
    user = db_manager.get_twitter_user(user_id)
    access_token = user["twitter_access_token"]
    expires_at = user["expires_at"]
    expiry_date = datetime.fromisoformat(expires_at)
    now = datetime.now().replace(tzinfo=expiry_date.tzinfo)
    print(f"Access token expires at: {expiry_date}\nIt is currently {now}")
    if now > expiry_date:
        access_token = auth.refresh_token(refresh_token=user["twitter_refresh_token"])
        save_to_db(user_id, access_token, user["twitter_refresh_token"])
    client = tweepy.Client(access_token["access_token"])
    me = client.get_me(user_auth=False)
    print(f"Me is {me}")

    # get tweets
    return get_tweets(client)


def get_tweets(client: tweepy.Client):
    public_tweets = client.get_home_timeline(max_results=1)
    print(public_tweets)
    print(f"Just in case that last one sucked\n{json.dumps(public_tweets)}")
    return public_tweets


def save_to_db(user_id, access_token, refresh_token):
    # Code to save tokens to database
    db_manager.add_twitter_user(
        user_id=user_id,
        access_token=access_token,
        refresh_token=refresh_token,
    )
    print("Stored user credentials in database")


if __name__ == "__main__":
    app.run(debug=True, port=5172, ssl_context=("localhost.crt", "localhost.key"))
```

**Comment by Harmon758** [comment] 2023-08-03 04:16
If you don't need to use OAuth 2.0, then I would recommend just using OAuth 1.0a. It's much simpler, especially if you don't need to authenticate as other users.

Regardless, you're setting `access_token` with these two lines:
```py
    user = db_manager.get_twitter_user(user_id)
    access_token = user["twitter_access_token"]
 ```
and I can't tell from this code what `access_token` ends up being here.
This isn't reproducible.

**Comment by ZachHandley** [comment] 2023-08-03 04:20
@Harmon758 I was using OAuth 1.0a, I know it's much easier, and it was giving me an error about being unauthenticated. The `twitter_access_token` in the database is the full response from the OAuth2.0 with the `type: Bearer`, `refresh_token` etc.

**Comment by ZachHandley** [comment] 2023-08-03 04:21
here's the database code too
```

DATABASES = Databases(CLIENT)


class DBManager:
    def __init__(self):
        self.client = CLIENT
        self.database = DATABASES

    def add_twitter_user(self, user_id: str, access_token: str, refresh_token: str):
        """
        This function will add a Twitter user to the database.

        :param user_id: The ID of the user that should be added.
        :param access_token: The access token of the user that should be added.
        :param access_token_secret: The access token secret of the user that should be added.
        """

        expires_at = datetime.now() + timedelta(seconds=access_token["expires_in"])
        print(
            f"It is currently {datetime.now()}\nAccess token expires at: {expires_at}"
        )
        data = json.dumps(
            {
                "twitter_access_token": json.dumps(access_token),
                "twitter_refresh_token": refresh_token,
                "expires_at": expires_at.isoformat(),
            }
        )
        userExists = self.check_twitter_user(user_id)
        if userExists:
            user = self.database.update_document(
                DB_ID,
                "twitter_user",
                user_id,
                data=data,
            )
        else:
            user = self.database.create_document(
                DB_ID,
                "twitter_user",
                user_id,
                data=data,
            )
        return user["$id"]

    def get_twitter_user(self, user_id: str):
        """
        This function will get a Twitter user from the database.

        :param user_id: The ID of the user that should be added.
        """
        try:
            user = self.database.get_document(DB_ID, "twitter_user", user_id)
            user["twitter_access_token"] = json.loads(user["twitter_access_token"])
            return user
        except:
            return None

    def check_twitter_user(self, user_id: str) -> bool:
        """
        This function will check if a user has authenticated with Twitter and we have what we need
        """
        user = self.database.get_document(DB_ID, "twitter_user", user_id)
        return user != None

    def store_tweet(self, user_id: str, tweet: str):
        """
        This function will write a tweet to the database
        """

    def write_tweet(self, user_id: str, tweet: str):
        """
        This function will write a tweet to the database and Twitter
        """

    def get_blacklisted_users(self) -> list:
        """
        This function will return the list of all blacklisted users.

        :param user_id: The ID of the user that should be checked.
        :return: True if the user is blacklisted, False if not.
        """
        users = self.database.list_documents(DB_ID, "blacklist")
        return users.documents

    def is_blacklisted(self, user_id: str) -> bool:
        """
        This function will check if a user is blacklisted.

        :param user_id: The ID of the user that should be checked.
        :return: True if the user is blacklisted, False if not.
        """
        try:
            self.database.get_document(DB_ID, "blacklist", user_id)
            return True
        except:
            return False

    def add_user_to_blacklist(self, user_id: str) -> int:
        """
        This function will add a user based on its ID in the blacklist.

        :param user_id: The ID of the user that should be added into the blacklist.
        """
        user = self.database.create_document(
            DB_ID, "blacklist", user_id, {"user_id": user_id}
        )
        return user["$id"]

    def remove_user_from_blacklist(self, user_id: str):
        """
        This function will remove a user based on its ID from the blacklist.

        :param user_id: The ID of the user that should be removed from the blacklist.
        """
        self.database.delete_document(DB_ID, "blacklist", user_id)

    def add_warn(
        self, user_id: str, server_id: str, moderator_id: str, reason: str
    ) -> int:
        """
        This function will add a warn to the database.

        :param user_id: The ID of the user that should be warned.
        :param reason: The reason why the user should be warned.
        """
        warn = self.database.create_document(
            DB_ID,
            "warns",
            ID.unique(),
            {
                "user_id": user_id,
                "server_id": server_id,
                "moderator_id": moderator_id,
                "reason": reason,
            },
        )
        return warn["$id"]

    def remove_warn(self, warn_id: str, user_id: str, server_id: str):
        """
        This function will remove a warn from the database.

        :param warn_id: The ID of the warn.
        :param user_id: The ID of the user that was warned.
        :param server_id: The ID of the server where the user has been warned
        """
        self.database.delete_document(DB_ID, "warns", warn_id)

    def get_warnings(self, user_id: str, server_id: str) -> list:
        warns = self.database.list_documents(
            DB_ID,
            "warns",
            queries=[Query.equal("id", user_id), Query.equal("server_id", server_id)],
        )
        return warns.documents

    def get_warnings(self, user_id: str, server_id: int) -> dict:
        """
        This function will get all the warnings of a user.

        :param user_id: The ID of the user that should be checked.
        :param server_id: The ID of the server that should be checked.
        :return: A list of all the warnings of the user.
        """
        warns = self.database.list_documents(
            DB_ID,
            "warns",
            queries=[
                Query.equal("user_id", user_id),
                Query.equal("server_id", server_id),
            ],
        )
        return warns.documents
```

**Comment by Harmon758** [comment] 2023-08-03 04:33
> Here. I'll share the entire repo with you.

No need. Sorry, I just realized the error is occurring in `callback`, not `get_user_tweets`.
In `callback`, you're passing the entire response (which you're assigning to `access_token`) to `Client`, not just the access token:
```py
    access_token = auth.fetch_token(request.url)

    print(f"Access token: {access_token}")
    session["access_token"] = access_token
    refresh_token = access_token["refresh_token"]

    ...

    client = tweepy.Client(access_token)
    me = client.get_me(user_auth=False)
```

> which you should really clarify which access token you're talking about in the docs because the other one also has an access token

Unfortunately, this naming confliction originates from Twitter's API.
Authenticating with OAuth 2.0 Authorization Code Flow with PKCE (User Context) didn't use to be an option, so App-Only Bearer Tokens were the only way to authenticate with OAuth 2.0, which is why the parameter is still named `bearer_token`.
Whereas OAuth 1.0a access tokens have been used since long before Twitter API v2 even existed.
However, [the documentation for `Client`](https://tweepy.readthedocs.io/en/v4.14.0/client.html#tweepy.Client) clearly indicates what each parameter is used for.

> I was using OAuth 1.0a, I know it's much easier, and it was giving me an error about needing more permissions.

You'll have to provide the relevant code and/or full traceback for that error if you need help with it. Otherwise, it's impossible to tell what's happening.

**Closed** 2023-08-03 04:35 UTC
Labels: Question, Invalid
