### ISSUE TITLE
Cannot upload videos

### ISSUE THREAD

**Issue by Guuri11** [tweepy/tweepy#1340] opened 2020-03-14 15:24 UTC
I've trying it all to upload a video from my bot but I can't find the way.

Now my code to upload it is this
`video = api.media_upload('media/primer_infectado_tw.mp4')
api.status_update(media_ids=[video.media_id_string])`

but always returns this error

`Traceback (most recent call last):
  File ".\video_script.py", line 33, in <module>
    img = api.media_upload('primer_infectado_tw.mp4')
  File "C:\Users\guria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\api.py", line 200, in media_upload
    headers, post_data = API._pack_image(filename, 4883, form_field='media', f=f)
  File "C:\Users\guria\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\api.py", line 1322, in _pack_image
    raise TweepError('Invalid file type for image: %s' % file_type)
tweepy.error.TweepError: Invalid file type for image: video/mp4`

In docs says that I can upload a video, but how?

**Comment by fitnr** [comment] 2020-03-15 19:22
This is a duplicate of #640

**Comment by MichaelCurrin** [comment] 2020-05-10 13:15
Also relates to #655 which got brought up again in take 2 #672. That issue has open PR #929 (not updated since Feb) - that adds `'video/mp4` and has a long conversations with it.

This looks to be complex issue which a few people have looked at other the years.

**Comment by Harmon758** [comment] 2020-06-26 23:23
Duplicate of #640 

For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.

**Closed by Harmon758** 2020-06-26 23:23 UTC
