### ISSUE TITLE
Connection broken - OSError -104 - ECONNRESET - tweepy

### ISSUE THREAD

**Issue by VincentNaveenJ** [tweepy/tweepy#1527] opened 2021-02-14 16:49 UTC
Hi,

I am frequently (atleast once per day) getting connection broken issues like OSError -104 - ECONNRESET in tweepy.

Let me explain my scenario briefly:   I am using twitter api version v1.1 standard edition. And using python streaming code in databricks notebook. With the help of tweepy package, we are connected with twitter api and getting streaming data as expected But connection has been breaking frequently.  We got one warning too as below:
/var/task/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!

Could anyone please suggest how can i fix this connection broken issue permanently?

Regards,
Vincent Naveen J

**Comment by Harmon758** [comment] 2021-02-20 05:08
Duplicate of #1113
This should now be handled by Tweepy, with https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f, in the latest development version on the master branch.

The RequestsDependencyWarning is an irrelevant warning about a dependency of requests (which is itself a dependency of Tweepy) not matching the expected version range.

**Closed by Harmon758** 2021-02-20 05:08 UTC
