### ISSUE TITLE
No module named 'tweepy.auth'

### ISSUE THREAD

**Issue by fernandomagda** [tweepy/tweepy#1004] opened 2018-02-21 16:09 UTC
Traceback (most recent call last):
  File "luckyBot.py", line 7, in <module>
    from tweepy.auth import OAuthHandler
ImportError: No module named 'tweepy.auth'

**Comment by tatianajiselle** [comment] 2018-06-21 18:23
in the newer versions of python, the . is replaces with a _

try tweepy_auth

**Comment by Harmon758** [comment] 2019-04-24 23:32
@tatianajiselle This is not true. [auth.py](https://github.com/tweepy/tweepy/blob/master/tweepy/auth.py) still exists as `tweepy.auth`.

This should have been fixed with https://github.com/tweepy/tweepy/commit/d9d5a8648d738c660fc0a457523d0083d03c2353 in v3.0.0, and I'm unable to reproduce this with Tweepy 3.7.0.
Make sure you don't have another file or module named "tweepy" in the project or in your path.

**Closed by Harmon758** 2019-04-24 23:32 UTC
