### ISSUE TITLE
Catastrophic Failure - Randomly

### ISSUE THREAD

**Issue by alexgurrola** [tweepy/tweepy#789] opened 2016-09-30 22:54 UTC
This issue occurs after running tweepy from anywhere between 1 minute - 24 hours, randomly.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alex/.local/lib/python3.5/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/home/alex/.local/lib/python3.5/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/home/alex/.local/lib/python3.5/site-packages/tweepy/streaming.py", line 324, in _read_loop
    self._data(next_status_obj)
  File "/home/alex/.local/lib/python3.5/site-packages/tweepy/streaming.py", line 297, in _data
    if self.listener.on_data(data) is False:
  File "/home/alex/.local/lib/python3.5/site-packages/tweepy/streaming.py", line 50, in on_data
    data = json.loads(raw_data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

My proposed solution is in the following Pull Request: https://github.com/tweepy/tweepy/pull/780

**Comment by Aaron1011** [comment] 2016-11-05 23:39
This should be fixed in https://github.com/tweepy/tweepy/commit/c1eddf1a5788ec4947d3a363dfe165ea599c31fc.

**Closed by Aaron1011** 2016-11-05 23:39 UTC

**Comment by Harmon758** [comment] 2019-04-25 08:15
Duplicate of #674.
