### ISSUE TITLE
ModelsReference missing from docs

### ISSUE THREAD

**Issue by rbroc** [tweepy/tweepy#1469] opened 2020-12-13 11:05 UTC
Here, Tweepy docs point to additional information on Models being available in `ModelsReference` docs
http://docs.tweepy.org/en/latest/getting_started.html?highlight=ModelsReference#models
However, `ModelsReference` docs are nowhere to be found. 
Would be rather crucial to have 🙂

**Comment by Harmon758** [comment] 2020-12-15 04:50
Duplicate of #720

**Closed by Harmon758** 2020-12-15 04:50 UTC
