### ISSUE TITLE
create_block() method not working?

### ISSUE THREAD

**Issue by ssrzz** [tweepy/tweepy#1246] opened 2019-07-28 07:30 UTC
I tried to use the `API.create_block(id/screen_name/user_id)` method to block some promoted accounts, but it did not work for me. 
My codes:
```python
auth = tweepy.OAuthHandler(my_key, my_secret)
auth.set_access_token(access_token,  access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

api.create_block('SuperGirlPro')   # Not working 
api.create_block(635943302)  # Not working too
```
I tried for several times, waited for 10+ minutes, and then checked the "blocked" account, but it is not in my black list. 
Did I miss something ?

**Comment by Harmon758** [comment] 2019-07-28 23:45
I'm unable to reproduce this.
Both `api.create_block('SuperGirlPro')` and `api.create_block(635943302)` work to block that user.

The documentation for the [POST blocks/create endpoint](https://developer.twitter.com/en/docs/accounts-and-users/mute-block-report-users/api-reference/post-blocks-create) that [`API.create_block`](https://tweepy.readthedocs.io/en/latest/api.html#API.create_block) uses *does* specify that `id` is not a normal parameter and that it should instead be passed to block/create/:id instead, but I believe this is outdated.

Are you encountering any errors? How are you determining if they've been successfully blocked?

**Comment by ssrzz** [comment] 2019-07-29 00:05
> I'm unable to reproduce this.
> Both `api.create_block('SuperGirlPro')` and `api.create_block(635943302)` work to block that user.
> 
> The documentation for the [POST blocks/create endpoint](https://developer.twitter.com/en/docs/accounts-and-users/mute-block-report-users/api-reference/post-blocks-create) that [`API.create_block`](https://tweepy.readthedocs.io/en/latest/api.html#API.create_block) uses _does_ specify that `id` is not a normal parameter and that it should instead be passed to block/create/:id instead, but I believe this is outdated.
> 
> Are you encountering any errors? How are you determining if they've been successfully blocked?

Thanks for your prompt reply. I just tried again, and both way `api.create_block(screen_name)  api.create_block(userid)`  work now. 

Could it possibly be I've reached my daily rate limit or something (I deleted lots of old tweets with tweeps yesterday), so the API no longer respond?

**Comment by Harmon758** [comment] 2019-07-29 00:11
It's possible that you hit a rate limit.
With `wait_on_rate_limit` set to `True`, this would cause the call to `API.create_block` to wait for that rate limit. If your calls to the method never finished executing, that's likely what happened. However, with `wait_on_rate_limit_notify` set to `True`, it should have been logged.

I'm going to close the issue now, since you're no longer able to reproduce it.

**Closed by Harmon758** 2019-07-29 00:11 UTC
Labels: Need Follow-Up, No Reproduction, Question
