### ISSUE TITLE
Is it possible to upload videos?

### ISSUE THREAD

**Issue by umar13893** [tweepy/tweepy#1322] opened 2020-01-29 11:23 UTC
I have tried many methods to upload videos using Tweepy but nothing worked for me. I also looked at other issues.

I am getting this error: Invalid file type for image: video/mp4

**Comment by Harmon758** [comment] 2020-02-13 09:15
Duplicate of #640

**Closed by Harmon758** 2020-02-13 09:15 UTC

**Comment by MuhBayu** [comment] 2020-03-26 14:32
Hi, I get the same error

> Invalid file type for image: video/mp4

I use version 3.8.0 of Tweepy
is there any solution?
