### ISSUE TITLE
Direct messaging not working

### ISSUE THREAD

**Issue by rohitfarmer** [tweepy/tweepy#1115] opened 2018-10-15 04:17 UTC
Hi all, I am getting `tweepy.error.TweepError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]
` . I am presuming this is due to Twitter API changes. Any fix?

**Comment by elg34** [comment] 2018-10-24 19:02
I used this fix here and it works well in 3.6.0
https://github.com/tweepy/tweepy/issues/1081

**Comment by Harmon758** [comment] 2019-04-28 03:08
Duplicate of #1081

**Closed by Harmon758** 2019-04-28 03:08 UTC
