### ISSUE TITLE
Getting error in importing tweepy

### ISSUE THREAD

**Issue by iteachmachines** [tweepy/tweepy#1127] opened 2018-11-07 08:55 UTC
Hello i am new to python and i am enjoying it till now But unfortunately i've been facing an issue so here it goes.

import  tweepy
from textblob import TextBlob
consumer_key=" "
consumer_secret=" "
access_token=""
access_token_secret=""

auth=tweepy.OAuthHandler(consumer_key,consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api=tweepy.API(auth)

public_tweets = api.search('Narendra Modi')
for tweet in public_tweets:
    print(tweet.text)
    analysis = TextBlob(tweet.text)
    print(analysis)

I am using Python 3.7. And the error is given in the following code.

C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/Lenovo/.PyCharmCE2018.1/config/scratches/scratch_2.py
Traceback (most recent call last):
  File "C:/Users/Lenovo/.PyCharmCE2018.1/config/scratches/scratch_2.py", line 1, in <module>
    import  tweepy
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\tweepy\__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python37\site-packages\tweepy\streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax

Process finished with exit code 1

**Comment by Harmon758** [comment] 2018-11-07 22:11
Duplicate of #1017 and fixed with #1042.
When submitting issues, please make sure you're on the most recent development version.
Otherwise, see #1063.

**Comment by hugovk** [comment] 2018-11-28 10:23
There is now a Tweepy release supporting Python 3.7.

https://pypi.org/project/tweepy/3.7.0/
https://github.com/tweepy/tweepy/releases/tag/3.7.0

This issue can be closed.

**Closed** 2019-04-24 16:51 UTC
Labels: Duplicate
