### ISSUE TITLE
Timeouts and Aborted Connections after running code for long times

### ISSUE THREAD

**Issue by tednopple** [tweepy/tweepy#617] opened 2015-06-05 15:11 UTC
I am using Twitter API to scan through tweets and users, but because of Twitter's API limits, scanning thousands of users/tweets can take hours. Fine. However, when I run Twitter API code through Python using Tweepy, after a few hours of the code running the code gets interrupted and I get one of two error messages:

tweepy.error.TweepError: Failed to send request: ('Connection aborted.', error(54, 'Connection reset by peer'))

Another error:

tweepy.error.TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=60)

It seems Twitter has a timeout limit that stops access after a certain point? Or not? Is this a Twitter API issue, or a Tweepy one?

This doesn't happen for small sizes, only when the code has to spend more than about an hour running. Of course one sees the problem with walking away from script that should take hours to run, only to come back and find that it's aborted partway through.

No one seems to know why this happens. Posted on several forums and spoken to several people..Could be a bug.

**Comment by jamesonwatts** [comment] 2015-07-02 17:24
Any luck with this? I'm having the same problem

**Comment by natejlong** [comment] 2015-07-07 18:50
Also having this problem unfortunately

**Comment by ThaWeatherman** [comment] 2015-07-22 02:25
Bump, since I am too QQ

**Comment by mustekito** [comment] 2015-07-25 09:32
I'm getting this error also

**Comment by astreim** [comment] 2015-08-04 22:56
Me too. Any help?

**Comment by eabanoz** [comment] 2015-08-20 13:03
Besides these errors, I have also gotten this error code;

RATE LIMIT - waiting 15 minutes...
Traceback (most recent call last):
  File "C:/Users/eabanoz/Desktop/Python_Scripts/Tweepy_Followers.py", line 73, in <module>
    print e.message[0]["code"]
TypeError: string indices must be integers, not str
TweepError Failed to send request: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))

Process finished with exit code 1

**Comment by ThaWeatherman** [comment] 2015-08-23 22:55
Just so everyone knows, the sixohsix twitter library works great. No issues with retry failing.

**Comment by lbvienna** [comment] 2015-09-07 20:34
Also getting this error. Anyone figure out a fix?

**Comment by scubjwu** [comment] 2015-09-22 02:11
I just got the same error two days ago. You can quickly reproduce the error by turning off your network connection. After briefly check the source codes of tweepy, I think the error is from request lib because the default timeout value in tweepy is set to be 60s. So just let your program sleep some time and make sure the network connection is Okay, and the codes should be able to be resume.

**Comment by jcapde87** [comment] 2015-09-22 12:24
I agree with scubjwu. To me it happened when the connection went off. I have "fixed" by catching ReadTimeoutError and ConnectionError within the Timeout except.
except (Timeout, ssl.SSLError, ReadTimeoutError, ConnectionError) as exc:

Note that ReadTimeoutError belongs to urllib3 packages
from requests.exceptions import Timeout, ConnectionError
from requests.packages.urllib3.exceptions import ReadTimeoutError

**Comment by tednopple** [comment] 2015-09-22 21:20
SORRY. This was for a client and Tweepy apparently couldn't care less about responding to the issue, plus the project was compete, so I stopped following the thread.  

Our workaround was to divide the tweets up into smaller batches. We ran the code several times at once using different keys and smaller batches, then join the files later.

For future projects I probably won't use Tweepy, due to lack of support. We were just in too deep to turn to another library this time.

Though, after reading the thread, it looks like it could be a connection issue. We were working on company server so maybe connection dropped every once in a while, but I seem to recall this happening on a home computer as well and someone with higher expertise saying this was not the case. 

Solutions so far: 
-@jcapde87 's Try/Except solution also seems like a good idea. 
-Use another library (Twitter)
-Divide data/calls into smaller batches and combine results later.

:(

**Comment by scubjwu** [comment] 2015-09-22 22:22
Hi @tednopple. I am just curious why using smaller batches would help ;-) Is it because smaller batches will shorter your time to process the data, so that the codes won't be timed out? Actually my codes just fetch the data from twitter and store it into database, so the data processing time is negligible. My feeling is the time out error may be raised by the rate limitation problem. You could always try to catch the exception and let the codes resume after sleeping for a while.

**Comment by tednopple** [comment] 2015-09-22 22:28
Yes, I think smaller batches just cut the processing time down. We were scanning followers. People with hundreds of thousands of followers caused the time out. So we divided the list to process less than 100,000 at a time

We wrote an exception to catch rate limits and wait the required 15 minutes. Despite this, the code would just abort all together with large data after hours of running.

**Comment by agklein1** [comment] 2015-09-25 21:00
Thanks @jcapde87. Big help.

**Comment by akisxyz** [comment] 2015-12-25 07:21
Thanks, @jcapde87 and @ccphillippi.

**Comment by allo-** [comment] 2016-03-08 17:23
I've got another error message to add:

    File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 149, in execute
        raise TweepError('Failed to send request: %s' % e)
    tweepy.error.TweepError: Failed to send request: [Errno 110] Connection timed out

Another wish:
Can you split the TweepError into more detailed Exceptions? Like ``TweepyTimeout(TweepError)``, so it can be caught for a retry?

**Comment by dclester11** [comment] 2016-04-30 02:22
I was having this ReadTimeOutError issue. I resolved this issue by catching the TweepError. @allo- you can access the TweepError's attribute (reason, response, api_code) to more specifically handle TweepError. In the particular error of 'Failed to send request' (e.g., raised in line 189), TweepError object only has reason. 

In the try except block, I added:

 except TweepError as e:
            if 'Failed to send request:' in e.reason:
                print "Time out error caught."
                time.sleep(180)
                continue

I have a while loop that wraps around the try except block. So whenever this TweepError is raised, the code sleeps for 180 sec. and continue executing the while loop. You can test this by running the code without internet access. Within that 180 sec, re connect the internet, and it should work.

**Comment by hwchung** [comment] 2016-04-30 02:22
I was having this ReadTimeOutError issue. I resolved this issue by catching the TweepError. @allo- you can access the TweepError's attribute (reason, response, api_code) to more specifically handle TweepError. In the particular error of 'Failed to send request' (e.g., raised in line 189), TweepError object only has reason.

In the try except block, I added:

except TweepError as e:
if 'Failed to send request:' in e.reason:
print "Time out error caught."
time.sleep(180)
continue

I have a while loop that wraps around the try except block. So whenever this TweepError is raised, the code sleeps for 180 sec. and continue executing the while loop. You can test this by running the code without internet access. Within that 180 sec, re connect the internet, and it should work.

**Comment by ZeerakW** [comment] 2016-07-04 22:00
Interestingly, I've found that @jcapde87's solution isn't working in python3, anyone else have the same experience?

**Comment by raiprabh** [comment] 2016-07-28 07:58
A quick query, can't we specify a longer timeout in api.timeout in Tweepy object rather than manually handling the error first and then using time.sleep? Since in 188th line in binder.py the following line is specified:

resp = self.session.request(self.method, full_url, data=self.post_data, timeout=self.api.timeout,auth=auth,
proxies=self.api.proxy)

**Comment by sam-s** [comment] 2016-10-09 16:47
I still observe this with python 2.7 and tweepy 3.5

**Comment by neuhaus** [comment] 2016-12-04 15:51
What's the best way to deal with broken connections?
I'm seeing this error when using the stream API (stream.filter() ) with tweepy 3.5.0 and python 3.5.2 after the program has run for a while.

**Comment by ZeerakW** [comment] 2016-12-04 15:57
@neuhaus It seems it's a timeout issue, so I would suggest setting a timeout for now.

**Comment by sam-s** [comment] 2016-12-04 16:57
@ZeerakW
Yes I did a month ago and commented there that it's an improvement but not a complete fix.

**Comment by kjoth** [comment] 2017-02-09 07:11
Is there any other alternative to Tweepy?

**Comment by sam-s** [comment] 2017-02-09 15:11
@kjoth : try [google](http://lmgtfy.com/?q=python+twitter+interface).
asking it here is not going to help you or anyone else.

**Comment by ThaWeatherman** [comment] 2017-02-14 10:27
@kjoth I answered this in a comment in this thread: https://github.com/tweepy/tweepy/issues/617#issuecomment-133950914

**Comment by kjoth** [comment] 2017-02-14 10:59
@ThaWeatherman Thats great. Thanks dude. I will check it out.

**Comment by neuhaus** [comment] 2017-02-21 13:31
A code example how to catch a timeout and re-establish connection etc would be great.

**Comment by KhoaDuongUQ** [comment] 2018-04-22 11:13
@jcapde Can you provide an example on how to catch a timeout and re-establish connection?

**Comment by KhoaDuongUQ** [comment] 2018-06-19 13:42
@greysonevins Apparently not, but you can follow the 'old' method (without using Cursor) in this [link](http://www.dealingdata.net/2016/07/23/PoGo-Series-Tweepy/) and it works perfectly.

**Comment by vzts** [comment] 2018-06-21 17:22
In my case I didn't want to mess up the code inside the package and my main thread was not doing anything, so I did the following after reading thorough the lib code:

```
from ssl import SSLError
from requests.exceptions import Timeout, ConnectionError
from urllib3.exceptions import ReadTimeoutError

listener = TweetsStreamListener(...)
stream = tweepy.Stream(...)

# create a zombie
while stream.running is False:
    try:
        # start stream synchronously
        logging.info("Started listening to twitter stream...")
        stream.filter(follow=target_accounts, async=False)
    except (Timeout, SSLError, ReadTimeoutError, ConnectionError) as e:
        logging.warning("Network error occurred. Keep calm and carry on.", str(e))
    except Exception as e:
        logging.error("Unexpected error!", e)
    finally:
        logging.info("Stream has crashed. System will restart twitter stream!")
logging.critical("Somehow zombie has escaped...!")

```

Hope it helps.

**Comment by vzts** [comment] 2018-06-21 17:48
It will be best if there's a PR for this one generalizing the caught exception [at here](https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L267). I've seen somebody already sent related PRs like https://github.com/tweepy/tweepy/pull/675 and https://github.com/tweepy/tweepy/pull/797. Maybe maintainers have different opinions or there's some tricky issues that only insiders really understand. Anyway, my example may be an easy workaround if it suits.

**Comment by lwahedi** [comment] 2018-06-28 03:21
I incorporated a fix for the problem when using the cursor (tested when collecting followers from a user with too many followers to successfully collect before). It's in my Tweepy fork here: 
`https://github.com/lwahedi/tweepy.git@master`

**Comment by lwahedi** [comment] 2018-07-09 23:50
Nevermind, it's not working, I just got lucky with timeouts. Will post again when I do manage to fix it.

**Comment by davekaj** [comment] 2019-04-01 01:25
vtzs solution worked. in the `try` statement I added in `time.sleep(5)` so that it doesn't try 100's of times in a few minutes

**Comment by t-duan** [comment] 2019-09-08 11:20
I tried to initiate api = tweepy.API(timeout=600) #default=60 every time after time.sleep(15*60). It seems to work.

**Comment by Kanav-119** [comment] 2020-05-19 10:28
HEY @jcapde  Can you plss write the entire catch block.

**Comment by saydus** [comment] 2020-09-10 13:24
I wonder why Tweepy has not addressed this issue yet. It persists even now. Will try solve timing out myself when I reach the boundary.

**Comment by danielp3011** [comment] 2021-01-08 10:54
2021, I still have the same issue.

**Comment by Harmon758** [comment] 2021-01-19 15:26
> This seems to be for streaming (which should now be resolved with [68e19cc](https://github.com/tweepy/tweepy/commit/68e19cc6b9b23d72369ca1520093770eb18a5a9f)) while this issue seems to be about `API` methods.

@KhoaDuongUQ

**Comment by dheeman00** [comment] 2021-03-01 18:43
I am facing this error while collecting the followers' information. Any suggestion will be helpful.

**Comment by Shigeri-39** [comment] 2021-03-21 10:10
@dheeman00 I'm currently facing the same issue while collecting follower and friend lists for my thesis. By any chance, were you able to come up with a solution yet?

**Comment by dheeman00** [comment] 2021-03-21 14:59
> @dheeman00 I'm currently facing the same issue while collecting follower and friend lists for my thesis. By any chance, were you able to come up with a solution yet?

Well one way to resolve the issue by running your extraction in a While True loop with a try and except block in it. In that way if you encounter any issues it will pause for a moment and continue the extraction again.

**Comment by Shigeri-39** [comment] 2021-03-21 16:04
@dheeman00 Yeah, I was able to get it working by now. Thanks tho. Unfortunately, now I'm facing a new issue that I haven't seen posted anywhere else before.

When I get this list of a person's follower_ids and then use the look_up users functions for 100 users at a time, both lists don't have the same amount of entries.

I figured out why by looking up every user_id individually. Apparently one out of 11k user ids seem to give an error. I did get the tweep error that the id does not match to a user. However, the issue is that when doing a user lookup for multiple ids , it does not return an error. In that case it only returns 99 lookup requests, resulting in a different length of lists.

Any idea why that is the case? Did you perhaps face the same issue at some point?

**Comment by dheeman00** [comment] 2021-03-21 19:00
> @dheeman00 Yeah, I was able to get it working by now. Thanks tho. Unfortunately, now I'm facing a new issue that I haven't seen posted anywhere else before.
> 
> When I get this list of a person's follower_ids and then use the look_up users functions for 100 users at a time, both lists don't have the same amount of entries.
> 
> I figured out why by looking up every user_id individually. Apparently one out of 11k user ids seem to give an error. I did get the tweep error that the id does not match to a user. However, the issue is that when doing a user lookup for multiple ids , it does not return an error. In that case it only returns 99 lookup requests, resulting in a different length of lists.
> 
> Any idea why that is the case? Did you perhaps face the same issue at some point?

Could you post your code where you are facing this issue. I can give you a better understanding when I can see this issue. 

But running followers is extraction and look up is will work out one after the another. As you can extract max of 15k id per 15 mins and in the case of look up it is just 100.

**Comment by Harmon758** [comment] 2021-06-07 23:21
Closing this in favor of #1606

**Closed by Harmon758** 2021-06-07 23:21 UTC
