### ISSUE TITLE
No support for Python 3.7

### ISSUE THREAD

**Issue by RyChrome** [tweepy/tweepy#1131] opened 2018-11-17 22:57 UTC
Currently, there is no support for Python 3.7, will there be in the future?

**Comment by Harmon758** [comment] 2018-11-17 23:13
Duplicate of #1063

**Comment by RyChrome** [comment] 2018-11-18 03:35
So can we do something about it lmao

**Comment by EmadFawaz** [comment] 2018-11-23 10:47
I am using Python 3.7 as well. I could not install the package. I hope an upgrade comes very soon.‎

**Comment by Harmon758** [comment] 2018-11-23 11:42
As stated in #1063, #1042 already fixed the issue.
Just upgrade to the development version from this GitHub repository.

**Comment by hugovk** [comment] 2018-11-28 10:20
This issue can now be closed because there is now a Tweepy release supporting Python 3.7.

Thank you, @joshthecoder!

**Closed** 2018-11-29 21:12 UTC
